// Auto-generated by ./tools/localedata/extract_icu_data.py

const char SCRIPT_CODES[][4] = {
    /* 0  */ {'A', 'r', 'a', 'b'},
    /* 1  */ {'A', 'r', 'm', 'n'},
    /* 2  */ {'B', 'e', 'n', 'g'},
    /* 3  */ {'C', 'a', 'n', 's'},
    /* 4  */ {'C', 'h', 'e', 'r'},
    /* 5  */ {'C', 'y', 'r', 'l'},
    /* 6  */ {'D', 'e', 'v', 'a'},
    /* 7  */ {'E', 't', 'h', 'i'},
    /* 8  */ {'G', 'e', 'o', 'r'},
    /* 9  */ {'G', 'r', 'e', 'k'},
    /* 10 */ {'G', 'u', 'j', 'r'},
    /* 11 */ {'G', 'u', 'r', 'u'},
    /* 12 */ {'H', 'a', 'n', 's'},
    /* 13 */ {'H', 'a', 'n', 't'},
    /* 14 */ {'H', 'e', 'b', 'r'},
    /* 15 */ {'J', 'p', 'a', 'n'},
    /* 16 */ {'K', 'h', 'm', 'r'},
    /* 17 */ {'K', 'n', 'd', 'a'},
    /* 18 */ {'K', 'o', 'r', 'e'},
    /* 19 */ {'L', 'a', 'o', 'o'},
    /* 20 */ {'L', 'a', 't', 'n'},
    /* 21 */ {'M', 'l', 'y', 'm'},
    /* 22 */ {'M', 'y', 'm', 'r'},
    /* 23 */ {'N', 'k', 'o', 'o'},
    /* 24 */ {'O', 'l', 'c', 'k'},
    /* 25 */ {'O', 'r', 'y', 'a'},
    /* 26 */ {'S', 'i', 'n', 'h'},
    /* 27 */ {'S', 'y', 'r', 'c'},
    /* 28 */ {'T', 'a', 'm', 'l'},
    /* 29 */ {'T', 'e', 'l', 'u'},
    /* 30 */ {'T', 'h', 'a', 'i'},
    /* 31 */ {'~', '~', '~', 'A'},
    /* 32 */ {'~', '~', '~', 'B'},
};


const std::unordered_map<uint32_t, uint8_t> LIKELY_SCRIPTS({
    {0x61660000u, 20u}, // af -> Latn
    {0x61664151u, 20u}, // af-AQ -> Latn
    {0x61664E41u, 20u}, // af-NA -> Latn
    {0x61665A41u, 20u}, // af-ZA -> Latn
    {0x616D0000u,  7u}, // am -> Ethi
    {0x616D4151u,  7u}, // am-AQ -> Ethi
    {0x616D4554u,  7u}, // am-ET -> Ethi
    {0x61720000u,  0u}, // ar -> Arab
    {0x61728400u,  0u}, // ar-001 -> Arab
    {0x61724145u,  0u}, // ar-AE -> Arab
    {0x61724151u,  0u}, // ar-AQ -> Arab
    {0x61724248u,  0u}, // ar-BH -> Arab
    {0x6172444Au,  0u}, // ar-DJ -> Arab
    {0x6172445Au,  0u}, // ar-DZ -> Arab
    {0x61724547u,  0u}, // ar-EG -> Arab
    {0x61724548u,  0u}, // ar-EH -> Arab
    {0x61724552u,  0u}, // ar-ER -> Arab
    {0x6172494Cu,  0u}, // ar-IL -> Arab
    {0x61724951u,  0u}, // ar-IQ -> Arab
    {0x61724A4Fu,  0u}, // ar-JO -> Arab
    {0x61724B4Du,  0u}, // ar-KM -> Arab
    {0x61724B57u,  0u}, // ar-KW -> Arab
    {0x61724C42u,  0u}, // ar-LB -> Arab
    {0x61724C59u,  0u}, // ar-LY -> Arab
    {0x61724D41u,  0u}, // ar-MA -> Arab
    {0x61724D52u,  0u}, // ar-MR -> Arab
    {0x61724F4Du,  0u}, // ar-OM -> Arab
    {0x61725053u,  0u}, // ar-PS -> Arab
    {0x61725141u,  0u}, // ar-QA -> Arab
    {0x61725341u,  0u}, // ar-SA -> Arab
    {0x61725344u,  0u}, // ar-SD -> Arab
    {0x6172534Fu,  0u}, // ar-SO -> Arab
    {0x61725353u,  0u}, // ar-SS -> Arab
    {0x61725359u,  0u}, // ar-SY -> Arab
    {0x61725444u,  0u}, // ar-TD -> Arab
    {0x6172544Eu,  0u}, // ar-TN -> Arab
    {0x61725842u, 32u}, // ar-XB -> ~~~B
    {0x61725945u,  0u}, // ar-YE -> Arab
    {0x61730000u,  2u}, // as -> Beng
    {0x61734151u,  2u}, // as-AQ -> Beng
    {0x6173494Eu,  2u}, // as-IN -> Beng
    {0xCE400000u, 20u}, // ast -> Latn
    {0xCE404151u, 20u}, // ast-AQ -> Latn
    {0xCE404553u, 20u}, // ast-ES -> Latn
    {0x617A0000u, 20u}, // az -> Latn
    {0x617A4151u, 20u}, // az-AQ -> Latn
    {0x617A415Au, 20u}, // az-AZ -> Latn
    {0x62650000u,  5u}, // be -> Cyrl
    {0x62654151u,  5u}, // be-AQ -> Cyrl
    {0x62654259u,  5u}, // be-BY -> Cyrl
    {0x62670000u,  5u}, // bg -> Cyrl
    {0x62674151u,  5u}, // bg-AQ -> Cyrl
    {0x62674247u,  5u}, // bg-BG -> Cyrl
    {0x88C10000u,  6u}, // bgc -> Deva
    {0x88C14151u,  6u}, // bgc-AQ -> Deva
    {0x88C1494Eu,  6u}, // bgc-IN -> Deva
    {0xB8E10000u,  6u}, // bho -> Deva
    {0xB8E14151u,  6u}, // bho-AQ -> Deva
    {0xB8E1494Eu,  6u}, // bho-IN -> Deva
    {0xB9610000u, 20u}, // blo -> Latn
    {0xB9614151u, 20u}, // blo-AQ -> Latn
    {0xB961424Au, 20u}, // blo-BJ -> Latn
    {0x626E0000u,  2u}, // bn -> Beng
    {0x626E4151u,  2u}, // bn-AQ -> Beng
    {0x626E4244u,  2u}, // bn-BD -> Beng
    {0x626E494Eu,  2u}, // bn-IN -> Beng
    {0x62720000u, 20u}, // br -> Latn
    {0x62724151u, 20u}, // br-AQ -> Latn
    {0x62724652u, 20u}, // br-FR -> Latn
    {0xDE210000u,  6u}, // brx -> Deva
    {0xDE214151u,  6u}, // brx-AQ -> Deva
    {0xDE21494Eu,  6u}, // brx-IN -> Deva
    {0x62730000u, 20u}, // bs -> Latn
    {0x62734151u, 20u}, // bs-AQ -> Latn
    {0x62734241u, 20u}, // bs-BA -> Latn
    {0x63610000u, 20u}, // ca -> Latn
    {0x63614144u, 20u}, // ca-AD -> Latn
    {0x63614151u, 20u}, // ca-AQ -> Latn
    {0x63614553u, 20u}, // ca-ES -> Latn
    {0x63614652u, 20u}, // ca-FR -> Latn
    {0x63614954u, 20u}, // ca-IT -> Latn
    {0x84820000u, 20u}, // ceb -> Latn
    {0x84824151u, 20u}, // ceb-AQ -> Latn
    {0x84825048u, 20u}, // ceb-PH -> Latn
    {0xC4E20000u,  4u}, // chr -> Cher
    {0xC4E24151u,  4u}, // chr-AQ -> Cher
    {0xC4E25553u,  4u}, // chr-US -> Cher
    {0x63730000u, 20u}, // cs -> Latn
    {0x63734151u, 20u}, // cs-AQ -> Latn
    {0x6373435Au, 20u}, // cs-CZ -> Latn
    {0xDA420000u,  3u}, // csw -> Cans
    {0xDA424151u,  3u}, // csw-AQ -> Cans
    {0xDA424341u,  3u}, // csw-CA -> Cans
    {0x63760000u,  5u}, // cv -> Cyrl
    {0x63764151u,  5u}, // cv-AQ -> Cyrl
    {0x63765255u,  5u}, // cv-RU -> Cyrl
    {0x63790000u, 20u}, // cy -> Latn
    {0x63794151u, 20u}, // cy-AQ -> Latn
    {0x63794742u, 20u}, // cy-GB -> Latn
    {0x64610000u, 20u}, // da -> Latn
    {0x64614151u, 20u}, // da-AQ -> Latn
    {0x6461444Bu, 20u}, // da-DK -> Latn
    {0x6461474Cu, 20u}, // da-GL -> Latn
    {0x64650000u, 20u}, // de -> Latn
    {0x64654151u, 20u}, // de-AQ -> Latn
    {0x64654154u, 20u}, // de-AT -> Latn
    {0x64654245u, 20u}, // de-BE -> Latn
    {0x64654348u, 20u}, // de-CH -> Latn
    {0x64654445u, 20u}, // de-DE -> Latn
    {0x64654954u, 20u}, // de-IT -> Latn
    {0x64654C49u, 20u}, // de-LI -> Latn
    {0x64654C55u, 20u}, // de-LU -> Latn
    {0xA1C30000u,  6u}, // doi -> Deva
    {0xA1C34151u,  6u}, // doi-AQ -> Deva
    {0xA1C3494Eu,  6u}, // doi-IN -> Deva
    {0x86430000u, 20u}, // dsb -> Latn
    {0x86434151u, 20u}, // dsb-AQ -> Latn
    {0x86434445u, 20u}, // dsb-DE -> Latn
    {0x656C0000u,  9u}, // el -> Grek
    {0x656C4151u,  9u}, // el-AQ -> Grek
    {0x656C4359u,  9u}, // el-CY -> Grek
    {0x656C4752u,  9u}, // el-GR -> Grek
    {0x656E0000u, 20u}, // en -> Latn
    {0x656E8400u, 20u}, // en-001 -> Latn
    {0x656E80A1u, 20u}, // en-150 -> Latn
    {0x656E4145u, 20u}, // en-AE -> Latn
    {0x656E4147u, 20u}, // en-AG -> Latn
    {0x656E4149u, 20u}, // en-AI -> Latn
    {0x656E4151u, 20u}, // en-AQ -> Latn
    {0x656E4153u, 20u}, // en-AS -> Latn
    {0x656E4154u, 20u}, // en-AT -> Latn
    {0x656E4155u, 20u}, // en-AU -> Latn
    {0x656E4242u, 20u}, // en-BB -> Latn
    {0x656E4245u, 20u}, // en-BE -> Latn
    {0x656E4249u, 20u}, // en-BI -> Latn
    {0x656E424Du, 20u}, // en-BM -> Latn
    {0x656E4253u, 20u}, // en-BS -> Latn
    {0x656E4257u, 20u}, // en-BW -> Latn
    {0x656E425Au, 20u}, // en-BZ -> Latn
    {0x656E4341u, 20u}, // en-CA -> Latn
    {0x656E4343u, 20u}, // en-CC -> Latn
    {0x656E4348u, 20u}, // en-CH -> Latn
    {0x656E434Bu, 20u}, // en-CK -> Latn
    {0x656E434Du, 20u}, // en-CM -> Latn
    {0x656E4358u, 20u}, // en-CX -> Latn
    {0x656E4359u, 20u}, // en-CY -> Latn
    {0x656E4445u, 20u}, // en-DE -> Latn
    {0x656E4447u, 20u}, // en-DG -> Latn
    {0x656E444Bu, 20u}, // en-DK -> Latn
    {0x656E444Du, 20u}, // en-DM -> Latn
    {0x656E4552u, 20u}, // en-ER -> Latn
    {0x656E4649u, 20u}, // en-FI -> Latn
    {0x656E464Au, 20u}, // en-FJ -> Latn
    {0x656E464Bu, 20u}, // en-FK -> Latn
    {0x656E464Du, 20u}, // en-FM -> Latn
    {0x656E4742u, 20u}, // en-GB -> Latn
    {0x656E4744u, 20u}, // en-GD -> Latn
    {0x656E4747u, 20u}, // en-GG -> Latn
    {0x656E4748u, 20u}, // en-GH -> Latn
    {0x656E4749u, 20u}, // en-GI -> Latn
    {0x656E474Du, 20u}, // en-GM -> Latn
    {0x656E4755u, 20u}, // en-GU -> Latn
    {0x656E4759u, 20u}, // en-GY -> Latn
    {0x656E484Bu, 20u}, // en-HK -> Latn
    {0x656E4944u, 20u}, // en-ID -> Latn
    {0x656E4945u, 20u}, // en-IE -> Latn
    {0x656E494Cu, 20u}, // en-IL -> Latn
    {0x656E494Du, 20u}, // en-IM -> Latn
    {0x656E494Eu, 20u}, // en-IN -> Latn
    {0x656E494Fu, 20u}, // en-IO -> Latn
    {0x656E4A45u, 20u}, // en-JE -> Latn
    {0x656E4A4Du, 20u}, // en-JM -> Latn
    {0x656E4B45u, 20u}, // en-KE -> Latn
    {0x656E4B49u, 20u}, // en-KI -> Latn
    {0x656E4B4Eu, 20u}, // en-KN -> Latn
    {0x656E4B59u, 20u}, // en-KY -> Latn
    {0x656E4C43u, 20u}, // en-LC -> Latn
    {0x656E4C52u, 20u}, // en-LR -> Latn
    {0x656E4C53u, 20u}, // en-LS -> Latn
    {0x656E4D47u, 20u}, // en-MG -> Latn
    {0x656E4D48u, 20u}, // en-MH -> Latn
    {0x656E4D4Fu, 20u}, // en-MO -> Latn
    {0x656E4D50u, 20u}, // en-MP -> Latn
    {0x656E4D53u, 20u}, // en-MS -> Latn
    {0x656E4D54u, 20u}, // en-MT -> Latn
    {0x656E4D55u, 20u}, // en-MU -> Latn
    {0x656E4D56u, 20u}, // en-MV -> Latn
    {0x656E4D57u, 20u}, // en-MW -> Latn
    {0x656E4D59u, 20u}, // en-MY -> Latn
    {0x656E4E41u, 20u}, // en-NA -> Latn
    {0x656E4E46u, 20u}, // en-NF -> Latn
    {0x656E4E47u, 20u}, // en-NG -> Latn
    {0x656E4E4Cu, 20u}, // en-NL -> Latn
    {0x656E4E52u, 20u}, // en-NR -> Latn
    {0x656E4E55u, 20u}, // en-NU -> Latn
    {0x656E4E5Au, 20u}, // en-NZ -> Latn
    {0x656E5047u, 20u}, // en-PG -> Latn
    {0x656E5048u, 20u}, // en-PH -> Latn
    {0x656E504Bu, 20u}, // en-PK -> Latn
    {0x656E504Eu, 20u}, // en-PN -> Latn
    {0x656E5052u, 20u}, // en-PR -> Latn
    {0x656E5057u, 20u}, // en-PW -> Latn
    {0x656E5257u, 20u}, // en-RW -> Latn
    {0x656E5342u, 20u}, // en-SB -> Latn
    {0x656E5343u, 20u}, // en-SC -> Latn
    {0x656E5344u, 20u}, // en-SD -> Latn
    {0x656E5345u, 20u}, // en-SE -> Latn
    {0x656E5347u, 20u}, // en-SG -> Latn
    {0x656E5348u, 20u}, // en-SH -> Latn
    {0x656E5349u, 20u}, // en-SI -> Latn
    {0x656E534Cu, 20u}, // en-SL -> Latn
    {0x656E5353u, 20u}, // en-SS -> Latn
    {0x656E5358u, 20u}, // en-SX -> Latn
    {0x656E535Au, 20u}, // en-SZ -> Latn
    {0x656E5443u, 20u}, // en-TC -> Latn
    {0x656E544Bu, 20u}, // en-TK -> Latn
    {0x656E544Fu, 20u}, // en-TO -> Latn
    {0x656E5454u, 20u}, // en-TT -> Latn
    {0x656E5456u, 20u}, // en-TV -> Latn
    {0x656E545Au, 20u}, // en-TZ -> Latn
    {0x656E5547u, 20u}, // en-UG -> Latn
    {0x656E554Du, 20u}, // en-UM -> Latn
    {0x656E5553u, 20u}, // en-US -> Latn
    {0x656E5643u, 20u}, // en-VC -> Latn
    {0x656E5647u, 20u}, // en-VG -> Latn
    {0x656E5649u, 20u}, // en-VI -> Latn
    {0x656E5655u, 20u}, // en-VU -> Latn
    {0x656E5753u, 20u}, // en-WS -> Latn
    {0x656E5841u, 31u}, // en-XA -> ~~~A
    {0x656E5A41u, 20u}, // en-ZA -> Latn
    {0x656E5A4Du, 20u}, // en-ZM -> Latn
    {0x656E5A57u, 20u}, // en-ZW -> Latn
    {0x65730000u, 20u}, // es -> Latn
    {0x6573A424u, 20u}, // es-419 -> Latn
    {0x65734151u, 20u}, // es-AQ -> Latn
    {0x65734152u, 20u}, // es-AR -> Latn
    {0x6573424Fu, 20u}, // es-BO -> Latn
    {0x65734252u, 20u}, // es-BR -> Latn
    {0x6573425Au, 20u}, // es-BZ -> Latn
    {0x6573434Cu, 20u}, // es-CL -> Latn
    {0x6573434Fu, 20u}, // es-CO -> Latn
    {0x65734352u, 20u}, // es-CR -> Latn
    {0x65734355u, 20u}, // es-CU -> Latn
    {0x6573444Fu, 20u}, // es-DO -> Latn
    {0x65734541u, 20u}, // es-EA -> Latn
    {0x65734543u, 20u}, // es-EC -> Latn
    {0x65734553u, 20u}, // es-ES -> Latn
    {0x65734751u, 20u}, // es-GQ -> Latn
    {0x65734754u, 20u}, // es-GT -> Latn
    {0x6573484Eu, 20u}, // es-HN -> Latn
    {0x65734943u, 20u}, // es-IC -> Latn
    {0x65734D58u, 20u}, // es-MX -> Latn
    {0x65734E49u, 20u}, // es-NI -> Latn
    {0x65735041u, 20u}, // es-PA -> Latn
    {0x65735045u, 20u}, // es-PE -> Latn
    {0x65735048u, 20u}, // es-PH -> Latn
    {0x65735052u, 20u}, // es-PR -> Latn
    {0x65735059u, 20u}, // es-PY -> Latn
    {0x65735356u, 20u}, // es-SV -> Latn
    {0x65735553u, 20u}, // es-US -> Latn
    {0x65735559u, 20u}, // es-UY -> Latn
    {0x65735645u, 20u}, // es-VE -> Latn
    {0x65740000u, 20u}, // et -> Latn
    {0x65744151u, 20u}, // et-AQ -> Latn
    {0x65744545u, 20u}, // et-EE -> Latn
    {0x65750000u, 20u}, // eu -> Latn
    {0x65754151u, 20u}, // eu-AQ -> Latn
    {0x65754553u, 20u}, // eu-ES -> Latn
    {0x66610000u,  0u}, // fa -> Arab
    {0x66614146u,  0u}, // fa-AF -> Arab
    {0x66614151u,  0u}, // fa-AQ -> Arab
    {0x66614952u,  0u}, // fa-IR -> Arab
    {0x66660000u, 20u}, // ff -> Latn
    {0x66664151u, 20u}, // ff-AQ -> Latn
    {0x66664246u, 20u}, // ff-BF -> Latn
    {0x6666434Du, 20u}, // ff-CM -> Latn
    {0x66664748u, 20u}, // ff-GH -> Latn
    {0x6666474Du, 20u}, // ff-GM -> Latn
    {0x6666474Eu, 20u}, // ff-GN -> Latn
    {0x66664757u, 20u}, // ff-GW -> Latn
    {0x66664C52u, 20u}, // ff-LR -> Latn
    {0x66664D52u, 20u}, // ff-MR -> Latn
    {0x66664E45u, 20u}, // ff-NE -> Latn
    {0x66664E47u, 20u}, // ff-NG -> Latn
    {0x6666534Cu, 20u}, // ff-SL -> Latn
    {0x6666534Eu, 20u}, // ff-SN -> Latn
    {0x66690000u, 20u}, // fi -> Latn
    {0x66694151u, 20u}, // fi-AQ -> Latn
    {0x66694649u, 20u}, // fi-FI -> Latn
    {0xAD050000u, 20u}, // fil -> Latn
    {0xAD054151u, 20u}, // fil-AQ -> Latn
    {0xAD055048u, 20u}, // fil-PH -> Latn
    {0x666F0000u, 20u}, // fo -> Latn
    {0x666F4151u, 20u}, // fo-AQ -> Latn
    {0x666F444Bu, 20u}, // fo-DK -> Latn
    {0x666F464Fu, 20u}, // fo-FO -> Latn
    {0x66720000u, 20u}, // fr -> Latn
    {0x66724151u, 20u}, // fr-AQ -> Latn
    {0x66724245u, 20u}, // fr-BE -> Latn
    {0x66724246u, 20u}, // fr-BF -> Latn
    {0x66724249u, 20u}, // fr-BI -> Latn
    {0x6672424Au, 20u}, // fr-BJ -> Latn
    {0x6672424Cu, 20u}, // fr-BL -> Latn
    {0x66724341u, 20u}, // fr-CA -> Latn
    {0x66724344u, 20u}, // fr-CD -> Latn
    {0x66724346u, 20u}, // fr-CF -> Latn
    {0x66724347u, 20u}, // fr-CG -> Latn
    {0x66724348u, 20u}, // fr-CH -> Latn
    {0x66724349u, 20u}, // fr-CI -> Latn
    {0x6672434Du, 20u}, // fr-CM -> Latn
    {0x6672444Au, 20u}, // fr-DJ -> Latn
    {0x6672445Au, 20u}, // fr-DZ -> Latn
    {0x66724652u, 20u}, // fr-FR -> Latn
    {0x66724741u, 20u}, // fr-GA -> Latn
    {0x66724746u, 20u}, // fr-GF -> Latn
    {0x6672474Eu, 20u}, // fr-GN -> Latn
    {0x66724750u, 20u}, // fr-GP -> Latn
    {0x66724751u, 20u}, // fr-GQ -> Latn
    {0x66724854u, 20u}, // fr-HT -> Latn
    {0x66724B4Du, 20u}, // fr-KM -> Latn
    {0x66724C55u, 20u}, // fr-LU -> Latn
    {0x66724D41u, 20u}, // fr-MA -> Latn
    {0x66724D43u, 20u}, // fr-MC -> Latn
    {0x66724D46u, 20u}, // fr-MF -> Latn
    {0x66724D47u, 20u}, // fr-MG -> Latn
    {0x66724D4Cu, 20u}, // fr-ML -> Latn
    {0x66724D51u, 20u}, // fr-MQ -> Latn
    {0x66724D52u, 20u}, // fr-MR -> Latn
    {0x66724D55u, 20u}, // fr-MU -> Latn
    {0x66724E43u, 20u}, // fr-NC -> Latn
    {0x66724E45u, 20u}, // fr-NE -> Latn
    {0x66725046u, 20u}, // fr-PF -> Latn
    {0x6672504Du, 20u}, // fr-PM -> Latn
    {0x66725245u, 20u}, // fr-RE -> Latn
    {0x66725257u, 20u}, // fr-RW -> Latn
    {0x66725343u, 20u}, // fr-SC -> Latn
    {0x6672534Eu, 20u}, // fr-SN -> Latn
    {0x66725359u, 20u}, // fr-SY -> Latn
    {0x66725444u, 20u}, // fr-TD -> Latn
    {0x66725447u, 20u}, // fr-TG -> Latn
    {0x6672544Eu, 20u}, // fr-TN -> Latn
    {0x66725655u, 20u}, // fr-VU -> Latn
    {0x66725746u, 20u}, // fr-WF -> Latn
    {0x66725954u, 20u}, // fr-YT -> Latn
    {0x66790000u, 20u}, // fy -> Latn
    {0x66794151u, 20u}, // fy-AQ -> Latn
    {0x66794E4Cu, 20u}, // fy-NL -> Latn
    {0x67610000u, 20u}, // ga -> Latn
    {0x67614151u, 20u}, // ga-AQ -> Latn
    {0x67614742u, 20u}, // ga-GB -> Latn
    {0x67614945u, 20u}, // ga-IE -> Latn
    {0x67640000u, 20u}, // gd -> Latn
    {0x67644151u, 20u}, // gd-AQ -> Latn
    {0x67644742u, 20u}, // gd-GB -> Latn
    {0x676C0000u, 20u}, // gl -> Latn
    {0x676C4151u, 20u}, // gl-AQ -> Latn
    {0x676C4553u, 20u}, // gl-ES -> Latn
    {0x67750000u, 10u}, // gu -> Gujr
    {0x67754151u, 10u}, // gu-AQ -> Gujr
    {0x6775494Eu, 10u}, // gu-IN -> Gujr
    {0x68610000u, 20u}, // ha -> Latn
    {0x68614151u, 20u}, // ha-AQ -> Latn
    {0x68614748u, 20u}, // ha-GH -> Latn
    {0x68614E45u, 20u}, // ha-NE -> Latn
    {0x68614E47u, 20u}, // ha-NG -> Latn
    {0x68650000u, 14u}, // he -> Hebr
    {0x68654151u, 14u}, // he-AQ -> Hebr
    {0x6865494Cu, 14u}, // he-IL -> Hebr
    {0x68690000u,  6u}, // hi -> Deva
    {0x68694151u,  6u}, // hi-AQ -> Deva
    {0x6869494Eu,  6u}, // hi-IN -> Deva
    {0x68720000u, 20u}, // hr -> Latn
    {0x68724151u, 20u}, // hr-AQ -> Latn
    {0x68724241u, 20u}, // hr-BA -> Latn
    {0x68724852u, 20u}, // hr-HR -> Latn
    {0x86470000u, 20u}, // hsb -> Latn
    {0x86474151u, 20u}, // hsb-AQ -> Latn
    {0x86474445u, 20u}, // hsb-DE -> Latn
    {0x68750000u, 20u}, // hu -> Latn
    {0x68754151u, 20u}, // hu-AQ -> Latn
    {0x68754855u, 20u}, // hu-HU -> Latn
    {0x68790000u,  1u}, // hy -> Armn
    {0x6879414Du,  1u}, // hy-AM -> Armn
    {0x68794151u,  1u}, // hy-AQ -> Armn
    {0x69640000u, 20u}, // id -> Latn
    {0x69644151u, 20u}, // id-AQ -> Latn
    {0x69644944u, 20u}, // id-ID -> Latn
    {0x69650000u, 20u}, // ie -> Latn
    {0x69654151u, 20u}, // ie-AQ -> Latn
    {0x69654545u, 20u}, // ie-EE -> Latn
    {0x69670000u, 20u}, // ig -> Latn
    {0x69674151u, 20u}, // ig-AQ -> Latn
    {0x69674E47u, 20u}, // ig-NG -> Latn
    {0x69730000u, 20u}, // is -> Latn
    {0x69734151u, 20u}, // is-AQ -> Latn
    {0x69734953u, 20u}, // is-IS -> Latn
    {0x69740000u, 20u}, // it -> Latn
    {0x69744151u, 20u}, // it-AQ -> Latn
    {0x69744348u, 20u}, // it-CH -> Latn
    {0x69744954u, 20u}, // it-IT -> Latn
    {0x6974534Du, 20u}, // it-SM -> Latn
    {0x69745641u, 20u}, // it-VA -> Latn
    {0x6A610000u, 15u}, // ja -> Jpan
    {0x6A614151u, 15u}, // ja-AQ -> Jpan
    {0x6A614A50u, 15u}, // ja-JP -> Jpan
    {0x6A690000u, 14u}, // ji -> Hebr
    {0x6A760000u, 20u}, // jv -> Latn
    {0x6A764151u, 20u}, // jv-AQ -> Latn
    {0x6A764944u, 20u}, // jv-ID -> Latn
    {0x6B610000u,  8u}, // ka -> Geor
    {0x6B614151u,  8u}, // ka-AQ -> Geor
    {0x6B614745u,  8u}, // ka-GE -> Geor
    {0x808A0000u, 20u}, // kea -> Latn
    {0x808A4151u, 20u}, // kea-AQ -> Latn
    {0x808A4356u, 20u}, // kea-CV -> Latn
    {0xBCCA0000u, 20u}, // kgp -> Latn
    {0xBCCA4151u, 20u}, // kgp-AQ -> Latn
    {0xBCCA4252u, 20u}, // kgp-BR -> Latn
    {0x6B6B0000u,  5u}, // kk -> Cyrl
    {0x6B6B4151u,  5u}, // kk-AQ -> Cyrl
    {0x6B6B4B5Au,  5u}, // kk-KZ -> Cyrl
    {0x6B6D0000u, 16u}, // km -> Khmr
    {0x6B6D4151u, 16u}, // km-AQ -> Khmr
    {0x6B6D4B48u, 16u}, // km-KH -> Khmr
    {0x6B6E0000u, 17u}, // kn -> Knda
    {0x6B6E4151u, 17u}, // kn-AQ -> Knda
    {0x6B6E494Eu, 17u}, // kn-IN -> Knda
    {0x6B6F0000u, 18u}, // ko -> Kore
    {0x6B6F4151u, 18u}, // ko-AQ -> Kore
    {0x6B6F434Eu, 18u}, // ko-CN -> Kore
    {0x6B6F4B50u, 18u}, // ko-KP -> Kore
    {0x6B6F4B52u, 18u}, // ko-KR -> Kore
    {0xA9CA0000u,  6u}, // kok -> Deva
    {0xA9CA4151u,  6u}, // kok-AQ -> Deva
    {0xA9CA494Eu,  6u}, // kok-IN -> Deva
    {0x6B730000u,  0u}, // ks -> Arab
    {0x6B734151u,  0u}, // ks-AQ -> Arab
    {0x6B73494Eu,  0u}, // ks-IN -> Arab
    {0x6B750000u, 20u}, // ku -> Latn
    {0x6B754151u, 20u}, // ku-AQ -> Latn
    {0x6B755452u, 20u}, // ku-TR -> Latn
    {0xD6EA0000u, 20u}, // kxv -> Latn
    {0xD6EA4151u, 20u}, // kxv-AQ -> Latn
    {0xD6EA494Eu, 20u}, // kxv-IN -> Latn
    {0x6B790000u,  5u}, // ky -> Cyrl
    {0x6B794151u,  5u}, // ky-AQ -> Cyrl
    {0x6B794B47u,  5u}, // ky-KG -> Cyrl
    {0x6C620000u, 20u}, // lb -> Latn
    {0x6C624151u, 20u}, // lb-AQ -> Latn
    {0x6C624C55u, 20u}, // lb-LU -> Latn
    {0xA50B0000u, 20u}, // lij -> Latn
    {0xA50B4151u, 20u}, // lij-AQ -> Latn
    {0xA50B4954u, 20u}, // lij-IT -> Latn
    {0xB98B0000u, 20u}, // lmo -> Latn
    {0xB98B4151u, 20u}, // lmo-AQ -> Latn
    {0xB98B4954u, 20u}, // lmo-IT -> Latn
    {0x6C6F0000u, 19u}, // lo -> Laoo
    {0x6C6F4151u, 19u}, // lo-AQ -> Laoo
    {0x6C6F4C41u, 19u}, // lo-LA -> Laoo
    {0x6C740000u, 20u}, // lt -> Latn
    {0x6C744151u, 20u}, // lt-AQ -> Latn
    {0x6C744C54u, 20u}, // lt-LT -> Latn
    {0x6C760000u, 20u}, // lv -> Latn
    {0x6C764151u, 20u}, // lv-AQ -> Latn
    {0x6C764C56u, 20u}, // lv-LV -> Latn
    {0xA00C0000u,  6u}, // mai -> Deva
    {0xA00C4151u,  6u}, // mai-AQ -> Deva
    {0xA00C494Eu,  6u}, // mai-IN -> Deva
    {0x6D690000u, 20u}, // mi -> Latn
    {0x6D694151u, 20u}, // mi-AQ -> Latn
    {0x6D694E5Au, 20u}, // mi-NZ -> Latn
    {0x6D6B0000u,  5u}, // mk -> Cyrl
    {0x6D6B4151u,  5u}, // mk-AQ -> Cyrl
    {0x6D6B4D4Bu,  5u}, // mk-MK -> Cyrl
    {0x6D6C0000u, 21u}, // ml -> Mlym
    {0x6D6C4151u, 21u}, // ml-AQ -> Mlym
    {0x6D6C494Eu, 21u}, // ml-IN -> Mlym
    {0x6D6E0000u,  5u}, // mn -> Cyrl
    {0x6D6E4151u,  5u}, // mn-AQ -> Cyrl
    {0x6D6E4D4Eu,  5u}, // mn-MN -> Cyrl
    {0xA1AC0000u,  2u}, // mni -> Beng
    {0xA1AC4151u,  2u}, // mni-AQ -> Beng
    {0xA1AC494Eu,  2u}, // mni-IN -> Beng
    {0x6D720000u,  6u}, // mr -> Deva
    {0x6D724151u,  6u}, // mr-AQ -> Deva
    {0x6D72494Eu,  6u}, // mr-IN -> Deva
    {0x6D730000u, 20u}, // ms -> Latn
    {0x6D734151u, 20u}, // ms-AQ -> Latn
    {0x6D73424Eu, 20u}, // ms-BN -> Latn
    {0x6D734944u, 20u}, // ms-ID -> Latn
    {0x6D734D59u, 20u}, // ms-MY -> Latn
    {0x6D735347u, 20u}, // ms-SG -> Latn
    {0x6D740000u, 20u}, // mt -> Latn
    {0x6D744151u, 20u}, // mt-AQ -> Latn
    {0x6D744D54u, 20u}, // mt-MT -> Latn
    {0x6D790000u, 22u}, // my -> Mymr
    {0x6D794151u, 22u}, // my-AQ -> Mymr
    {0x6D794D4Du, 22u}, // my-MM -> Mymr
    {0x6E620000u, 20u}, // nb -> Latn
    {0x6E624151u, 20u}, // nb-AQ -> Latn
    {0x6E624E4Fu, 20u}, // nb-NO -> Latn
    {0x6E62534Au, 20u}, // nb-SJ -> Latn
    {0xC86D0000u, 20u}, // nds -> Latn
    {0xC86D4151u, 20u}, // nds-AQ -> Latn
    {0xC86D4445u, 20u}, // nds-DE -> Latn
    {0xC86D4E4Cu, 20u}, // nds-NL -> Latn
    {0x6E650000u,  6u}, // ne -> Deva
    {0x6E654151u,  6u}, // ne-AQ -> Deva
    {0x6E65494Eu,  6u}, // ne-IN -> Deva
    {0x6E654E50u,  6u}, // ne-NP -> Deva
    {0x6E6C0000u, 20u}, // nl -> Latn
    {0x6E6C4151u, 20u}, // nl-AQ -> Latn
    {0x6E6C4157u, 20u}, // nl-AW -> Latn
    {0x6E6C4245u, 20u}, // nl-BE -> Latn
    {0x6E6C4251u, 20u}, // nl-BQ -> Latn
    {0x6E6C4357u, 20u}, // nl-CW -> Latn
    {0x6E6C4E4Cu, 20u}, // nl-NL -> Latn
    {0x6E6C5352u, 20u}, // nl-SR -> Latn
    {0x6E6C5358u, 20u}, // nl-SX -> Latn
    {0x6E6E0000u, 20u}, // nn -> Latn
    {0x6E6E4151u, 20u}, // nn-AQ -> Latn
    {0x6E6E4E4Fu, 20u}, // nn-NO -> Latn
    {0x6E6F0000u, 20u}, // no -> Latn
    {0x6E6F4151u, 20u}, // no-AQ -> Latn
    {0x6E6F4E4Fu, 20u}, // no-NO -> Latn
    {0xBA0D0000u, 23u}, // nqo -> Nkoo
    {0xBA0D4151u, 23u}, // nqo-AQ -> Nkoo
    {0xBA0D474Eu, 23u}, // nqo-GN -> Nkoo
    {0x6F630000u, 20u}, // oc -> Latn
    {0x6F634151u, 20u}, // oc-AQ -> Latn
    {0x6F634553u, 20u}, // oc-ES -> Latn
    {0x6F634652u, 20u}, // oc-FR -> Latn
    {0x6F720000u, 25u}, // or -> Orya
    {0x6F724151u, 25u}, // or-AQ -> Orya
    {0x6F72494Eu, 25u}, // or-IN -> Orya
    {0x70610000u, 11u}, // pa -> Guru
    {0x70614151u, 11u}, // pa-AQ -> Guru
    {0x7061494Eu, 11u}, // pa-IN -> Guru
    {0xB04F0000u, 20u}, // pcm -> Latn
    {0xB04F4151u, 20u}, // pcm-AQ -> Latn
    {0xB04F4E47u, 20u}, // pcm-NG -> Latn
    {0x706C0000u, 20u}, // pl -> Latn
    {0x706C4151u, 20u}, // pl-AQ -> Latn
    {0x706C504Cu, 20u}, // pl-PL -> Latn
    {0x9A2F0000u, 20u}, // prg -> Latn
    {0x9A2F4151u, 20u}, // prg-AQ -> Latn
    {0x9A2F504Cu, 20u}, // prg-PL -> Latn
    {0x70730000u,  0u}, // ps -> Arab
    {0x70734146u,  0u}, // ps-AF -> Arab
    {0x70734151u,  0u}, // ps-AQ -> Arab
    {0x7073504Bu,  0u}, // ps-PK -> Arab
    {0x70740000u, 20u}, // pt -> Latn
    {0x7074414Fu, 20u}, // pt-AO -> Latn
    {0x70744151u, 20u}, // pt-AQ -> Latn
    {0x70744252u, 20u}, // pt-BR -> Latn
    {0x70744348u, 20u}, // pt-CH -> Latn
    {0x70744356u, 20u}, // pt-CV -> Latn
    {0x70744751u, 20u}, // pt-GQ -> Latn
    {0x70744757u, 20u}, // pt-GW -> Latn
    {0x70744C55u, 20u}, // pt-LU -> Latn
    {0x70744D4Fu, 20u}, // pt-MO -> Latn
    {0x70744D5Au, 20u}, // pt-MZ -> Latn
    {0x70745054u, 20u}, // pt-PT -> Latn
    {0x70745354u, 20u}, // pt-ST -> Latn
    {0x7074544Cu, 20u}, // pt-TL -> Latn
    {0x71750000u, 20u}, // qu -> Latn
    {0x71754151u, 20u}, // qu-AQ -> Latn
    {0x7175424Fu, 20u}, // qu-BO -> Latn
    {0x71754543u, 20u}, // qu-EC -> Latn
    {0x71755045u, 20u}, // qu-PE -> Latn
    {0xA4110000u,  6u}, // raj -> Deva
    {0xA4114151u,  6u}, // raj-AQ -> Deva
    {0xA411494Eu,  6u}, // raj-IN -> Deva
    {0x726D0000u, 20u}, // rm -> Latn
    {0x726D4151u, 20u}, // rm-AQ -> Latn
    {0x726D4348u, 20u}, // rm-CH -> Latn
    {0x726F0000u, 20u}, // ro -> Latn
    {0x726F4151u, 20u}, // ro-AQ -> Latn
    {0x726F4D44u, 20u}, // ro-MD -> Latn
    {0x726F524Fu, 20u}, // ro-RO -> Latn
    {0x72750000u,  5u}, // ru -> Cyrl
    {0x72754151u,  5u}, // ru-AQ -> Cyrl
    {0x72754259u,  5u}, // ru-BY -> Cyrl
    {0x72754B47u,  5u}, // ru-KG -> Cyrl
    {0x72754B5Au,  5u}, // ru-KZ -> Cyrl
    {0x72754D44u,  5u}, // ru-MD -> Cyrl
    {0x72755255u,  5u}, // ru-RU -> Cyrl
    {0x72755541u,  5u}, // ru-UA -> Cyrl
    {0x73610000u,  6u}, // sa -> Deva
    {0x73614151u,  6u}, // sa-AQ -> Deva
    {0x7361494Eu,  6u}, // sa-IN -> Deva
    {0x9C120000u,  5u}, // sah -> Cyrl
    {0x9C124151u,  5u}, // sah-AQ -> Cyrl
    {0x9C125255u,  5u}, // sah-RU -> Cyrl
    {0xCC120000u, 24u}, // sat -> Olck
    {0xCC124151u, 24u}, // sat-AQ -> Olck
    {0xCC12494Eu, 24u}, // sat-IN -> Olck
    {0x73630000u, 20u}, // sc -> Latn
    {0x73634151u, 20u}, // sc-AQ -> Latn
    {0x73634954u, 20u}, // sc-IT -> Latn
    {0x73640000u,  0u}, // sd -> Arab
    {0x73644151u,  0u}, // sd-AQ -> Arab
    {0x7364494Eu,  6u}, // sd-IN -> Deva
    {0x7364504Bu,  0u}, // sd-PK -> Arab
    {0x73690000u, 26u}, // si -> Sinh
    {0x73694151u, 26u}, // si-AQ -> Sinh
    {0x73694C4Bu, 26u}, // si-LK -> Sinh
    {0x736B0000u, 20u}, // sk -> Latn
    {0x736B4151u, 20u}, // sk-AQ -> Latn
    {0x736B534Bu, 20u}, // sk-SK -> Latn
    {0x736C0000u, 20u}, // sl -> Latn
    {0x736C4151u, 20u}, // sl-AQ -> Latn
    {0x736C5349u, 20u}, // sl-SI -> Latn
    {0x736F0000u, 20u}, // so -> Latn
    {0x736F4151u, 20u}, // so-AQ -> Latn
    {0x736F444Au, 20u}, // so-DJ -> Latn
    {0x736F4554u, 20u}, // so-ET -> Latn
    {0x736F4B45u, 20u}, // so-KE -> Latn
    {0x736F534Fu, 20u}, // so-SO -> Latn
    {0x73710000u, 20u}, // sq -> Latn
    {0x7371414Cu, 20u}, // sq-AL -> Latn
    {0x73714151u, 20u}, // sq-AQ -> Latn
    {0x73714D4Bu, 20u}, // sq-MK -> Latn
    {0x7371584Bu, 20u}, // sq-XK -> Latn
    {0x73720000u,  5u}, // sr -> Cyrl
    {0x73724151u,  5u}, // sr-AQ -> Cyrl
    {0x73724241u,  5u}, // sr-BA -> Cyrl
    {0x73724D45u, 20u}, // sr-ME -> Latn
    {0x73725253u,  5u}, // sr-RS -> Cyrl
    {0x7372584Bu,  5u}, // sr-XK -> Cyrl
    {0x73750000u, 20u}, // su -> Latn
    {0x73754151u, 20u}, // su-AQ -> Latn
    {0x73754944u, 20u}, // su-ID -> Latn
    {0x73760000u, 20u}, // sv -> Latn
    {0x73764151u, 20u}, // sv-AQ -> Latn
    {0x73764158u, 20u}, // sv-AX -> Latn
    {0x73764649u, 20u}, // sv-FI -> Latn
    {0x73765345u, 20u}, // sv-SE -> Latn
    {0x73770000u, 20u}, // sw -> Latn
    {0x73774151u, 20u}, // sw-AQ -> Latn
    {0x73774344u, 20u}, // sw-CD -> Latn
    {0x73774B45u, 20u}, // sw-KE -> Latn
    {0x7377545Au, 20u}, // sw-TZ -> Latn
    {0x73775547u, 20u}, // sw-UG -> Latn
    {0xC7120000u, 27u}, // syr -> Syrc
    {0xC7124151u, 27u}, // syr-AQ -> Syrc
    {0xC7124951u, 27u}, // syr-IQ -> Syrc
    {0xC7125359u, 27u}, // syr-SY -> Syrc
    {0xAF320000u, 20u}, // szl -> Latn
    {0xAF324151u, 20u}, // szl-AQ -> Latn
    {0xAF32504Cu, 20u}, // szl-PL -> Latn
    {0x74610000u, 28u}, // ta -> Taml
    {0x74614151u, 28u}, // ta-AQ -> Taml
    {0x7461494Eu, 28u}, // ta-IN -> Taml
    {0x74614C4Bu, 28u}, // ta-LK -> Taml
    {0x74614D59u, 28u}, // ta-MY -> Taml
    {0x74615347u, 28u}, // ta-SG -> Taml
    {0x74650000u, 29u}, // te -> Telu
    {0x74654151u, 29u}, // te-AQ -> Telu
    {0x7465494Eu, 29u}, // te-IN -> Telu
    {0x74670000u,  5u}, // tg -> Cyrl
    {0x74674151u,  5u}, // tg-AQ -> Cyrl
    {0x7467544Au,  5u}, // tg-TJ -> Cyrl
    {0x74680000u, 30u}, // th -> Thai
    {0x74684151u, 30u}, // th-AQ -> Thai
    {0x74685448u, 30u}, // th-TH -> Thai
    {0x74690000u,  7u}, // ti -> Ethi
    {0x74694151u,  7u}, // ti-AQ -> Ethi
    {0x74694552u,  7u}, // ti-ER -> Ethi
    {0x74694554u,  7u}, // ti-ET -> Ethi
    {0x746B0000u, 20u}, // tk -> Latn
    {0x746B4151u, 20u}, // tk-AQ -> Latn
    {0x746B544Du, 20u}, // tk-TM -> Latn
    {0x746F0000u, 20u}, // to -> Latn
    {0x746F4151u, 20u}, // to-AQ -> Latn
    {0x746F544Fu, 20u}, // to-TO -> Latn
    {0x74720000u, 20u}, // tr -> Latn
    {0x74724151u, 20u}, // tr-AQ -> Latn
    {0x74724359u, 20u}, // tr-CY -> Latn
    {0x74725452u, 20u}, // tr-TR -> Latn
    {0x74740000u,  5u}, // tt -> Cyrl
    {0x74744151u,  5u}, // tt-AQ -> Cyrl
    {0x74745255u,  5u}, // tt-RU -> Cyrl
    {0x75670000u,  0u}, // ug -> Arab
    {0x75674151u,  0u}, // ug-AQ -> Arab
    {0x7567434Eu,  0u}, // ug-CN -> Arab
    {0x756B0000u,  5u}, // uk -> Cyrl
    {0x756B4151u,  5u}, // uk-AQ -> Cyrl
    {0x756B5541u,  5u}, // uk-UA -> Cyrl
    {0x75720000u,  0u}, // ur -> Arab
    {0x75724151u,  0u}, // ur-AQ -> Arab
    {0x7572494Eu,  0u}, // ur-IN -> Arab
    {0x7572504Bu,  0u}, // ur-PK -> Arab
    {0x757A0000u, 20u}, // uz -> Latn
    {0x757A4151u, 20u}, // uz-AQ -> Latn
    {0x757A555Au, 20u}, // uz-UZ -> Latn
    {0x88950000u, 20u}, // vec -> Latn
    {0x88954151u, 20u}, // vec-AQ -> Latn
    {0x88954954u, 20u}, // vec-IT -> Latn
    {0x76690000u, 20u}, // vi -> Latn
    {0x76694151u, 20u}, // vi-AQ -> Latn
    {0x7669564Eu, 20u}, // vi-VN -> Latn
    {0xD9950000u, 20u}, // vmw -> Latn
    {0xD9954151u, 20u}, // vmw-AQ -> Latn
    {0xD9954D5Au, 20u}, // vmw-MZ -> Latn
    {0x776F0000u, 20u}, // wo -> Latn
    {0x776F4151u, 20u}, // wo-AQ -> Latn
    {0x776F534Eu, 20u}, // wo-SN -> Latn
    {0x78680000u, 20u}, // xh -> Latn
    {0x78684151u, 20u}, // xh-AQ -> Latn
    {0x78685A41u, 20u}, // xh-ZA -> Latn
    {0xC5B70000u,  6u}, // xnr -> Deva
    {0xC5B74151u,  6u}, // xnr-AQ -> Deva
    {0xC5B7494Eu,  6u}, // xnr-IN -> Deva
    {0x796F0000u, 20u}, // yo -> Latn
    {0x796F4151u, 20u}, // yo-AQ -> Latn
    {0x796F424Au, 20u}, // yo-BJ -> Latn
    {0x796F4E47u, 20u}, // yo-NG -> Latn
    {0xAE380000u, 20u}, // yrl -> Latn
    {0xAE384151u, 20u}, // yrl-AQ -> Latn
    {0xAE384252u, 20u}, // yrl-BR -> Latn
    {0xAE38434Fu, 20u}, // yrl-CO -> Latn
    {0xAE385645u, 20u}, // yrl-VE -> Latn
    {0x92980000u, 13u}, // yue -> Hant
    {0x92984151u, 13u}, // yue-AQ -> Hant
    {0x9298434Eu, 12u}, // yue-CN -> Hans
    {0x9298484Bu, 13u}, // yue-HK -> Hant
    {0x7A610000u, 20u}, // za -> Latn
    {0x7A614151u, 20u}, // za-AQ -> Latn
    {0x7A61434Eu, 20u}, // za-CN -> Latn
    {0x7A680000u, 12u}, // zh -> Hans
    {0x7A684151u, 12u}, // zh-AQ -> Hans
    {0x7A68434Eu, 12u}, // zh-CN -> Hans
    {0x7A68484Bu, 13u}, // zh-HK -> Hant
    {0x7A684D4Fu, 13u}, // zh-MO -> Hant
    {0x7A685347u, 12u}, // zh-SG -> Hans
    {0x7A685457u, 13u}, // zh-TW -> Hant
    {0x7A750000u, 20u}, // zu -> Latn
    {0x7A754151u, 20u}, // zu-AQ -> Latn
    {0x7A755A41u, 20u}, // zu-ZA -> Latn
});

std::unordered_set<uint64_t> REPRESENTATIVE_LOCALES({
    0x61665A4145677970LLU, // af-Egyp-ZA
    0x61665A414C61746ELLU, // af-Latn-ZA
    0x616D455445677970LLU, // am-Egyp-ET
    0x616D455445746869LLU, // am-Ethi-ET
    0x6172454741726162LLU, // ar-Arab-EG
    0x6172454745677970LLU, // ar-Egyp-EG
    0x6173494E42656E67LLU, // as-Beng-IN
    0x6173494E45677970LLU, // as-Egyp-IN
    0xCE40455345677970LLU, // ast-Egyp-ES
    0xCE4045534C61746ELLU, // ast-Latn-ES
    0x617A415A45677970LLU, // az-Egyp-AZ
    0x617A415A4C61746ELLU, // az-Latn-AZ
    0x626542594379726CLLU, // be-Cyrl-BY
    0x6265425945677970LLU, // be-Egyp-BY
    0x626742474379726CLLU, // bg-Cyrl-BG
    0x6267424745677970LLU, // bg-Egyp-BG
    0x88C1494E44657661LLU, // bgc-Deva-IN
    0x88C1494E45677970LLU, // bgc-Egyp-IN
    0xB8E1494E44657661LLU, // bho-Deva-IN
    0xB8E1494E45677970LLU, // bho-Egyp-IN
    0xB961424A45677970LLU, // blo-Egyp-BJ
    0xB961424A4C61746ELLU, // blo-Latn-BJ
    0x626E424442656E67LLU, // bn-Beng-BD
    0x626E424445677970LLU, // bn-Egyp-BD
    0x6272465245677970LLU, // br-Egyp-FR
    0x627246524C61746ELLU, // br-Latn-FR
    0xDE21494E44657661LLU, // brx-Deva-IN
    0xDE21494E45677970LLU, // brx-Egyp-IN
    0x627342414379726CLLU, // bs-Cyrl-BA
    0x6273424145677970LLU, // bs-Egyp-BA
    0x627342414C61746ELLU, // bs-Latn-BA
    0x6361455345677970LLU, // ca-Egyp-ES
    0x636145534C61746ELLU, // ca-Latn-ES
    0x8482504845677970LLU, // ceb-Egyp-PH
    0x848250484C61746ELLU, // ceb-Latn-PH
    0xC4E2555343686572LLU, // chr-Cher-US
    0xC4E2555345677970LLU, // chr-Egyp-US
    0x6373435A45677970LLU, // cs-Egyp-CZ
    0x6373435A4C61746ELLU, // cs-Latn-CZ
    0xDA42434143616E73LLU, // csw-Cans-CA
    0xDA42434145677970LLU, // csw-Egyp-CA
    0x637652554379726CLLU, // cv-Cyrl-RU
    0x6376525545677970LLU, // cv-Egyp-RU
    0x6379474245677970LLU, // cy-Egyp-GB
    0x637947424C61746ELLU, // cy-Latn-GB
    0x6461444B45677970LLU, // da-Egyp-DK
    0x6461444B4C61746ELLU, // da-Latn-DK
    0x6465444545677970LLU, // de-Egyp-DE
    0x646544454C61746ELLU, // de-Latn-DE
    0xA1C3494E44657661LLU, // doi-Deva-IN
    0xA1C3494E45677970LLU, // doi-Egyp-IN
    0x8643444545677970LLU, // dsb-Egyp-DE
    0x864344454C61746ELLU, // dsb-Latn-DE
    0x656C475245677970LLU, // el-Egyp-GR
    0x656C47524772656BLLU, // el-Grek-GR
    0x656E555345677970LLU, // en-Egyp-US
    0x656E47424C61746ELLU, // en-Latn-GB
    0x656E55534C61746ELLU, // en-Latn-US
    0x6573455345677970LLU, // es-Egyp-ES
    0x657345534C61746ELLU, // es-Latn-ES
    0x65734D584C61746ELLU, // es-Latn-MX
    0x657355534C61746ELLU, // es-Latn-US
    0x6574454545677970LLU, // et-Egyp-EE
    0x657445454C61746ELLU, // et-Latn-EE
    0x6575455345677970LLU, // eu-Egyp-ES
    0x657545534C61746ELLU, // eu-Latn-ES
    0x6661495241726162LLU, // fa-Arab-IR
    0x6661495245677970LLU, // fa-Egyp-IR
    0x6666474E41646C6DLLU, // ff-Adlm-GN
    0x6666534E45677970LLU, // ff-Egyp-SN
    0x6666534E4C61746ELLU, // ff-Latn-SN
    0x6669464945677970LLU, // fi-Egyp-FI
    0x666946494C61746ELLU, // fi-Latn-FI
    0xAD05504845677970LLU, // fil-Egyp-PH
    0xAD0550484C61746ELLU, // fil-Latn-PH
    0x666F464F45677970LLU, // fo-Egyp-FO
    0x666F464F4C61746ELLU, // fo-Latn-FO
    0x6672465245677970LLU, // fr-Egyp-FR
    0x667246524C61746ELLU, // fr-Latn-FR
    0x66794E4C45677970LLU, // fy-Egyp-NL
    0x66794E4C4C61746ELLU, // fy-Latn-NL
    0x6761494545677970LLU, // ga-Egyp-IE
    0x676149454C61746ELLU, // ga-Latn-IE
    0x6764474245677970LLU, // gd-Egyp-GB
    0x676447424C61746ELLU, // gd-Latn-GB
    0x676C455345677970LLU, // gl-Egyp-ES
    0x676C45534C61746ELLU, // gl-Latn-ES
    0x6775494E45677970LLU, // gu-Egyp-IN
    0x6775494E47756A72LLU, // gu-Gujr-IN
    0x68614E4745677970LLU, // ha-Egyp-NG
    0x68614E474C61746ELLU, // ha-Latn-NG
    0x6865494C45677970LLU, // he-Egyp-IL
    0x6865494C48656272LLU, // he-Hebr-IL
    0x6869494E44657661LLU, // hi-Deva-IN
    0x6869494E45677970LLU, // hi-Egyp-IN
    0x6869494E4C61746ELLU, // hi-Latn-IN
    0x6872485245677970LLU, // hr-Egyp-HR
    0x687248524C61746ELLU, // hr-Latn-HR
    0x8647444545677970LLU, // hsb-Egyp-DE
    0x864744454C61746ELLU, // hsb-Latn-DE
    0x6875485545677970LLU, // hu-Egyp-HU
    0x687548554C61746ELLU, // hu-Latn-HU
    0x6879414D41726D6ELLU, // hy-Armn-AM
    0x6879414D45677970LLU, // hy-Egyp-AM
    0x6964494445677970LLU, // id-Egyp-ID
    0x696449444C61746ELLU, // id-Latn-ID
    0x6965454545677970LLU, // ie-Egyp-EE
    0x696545454C61746ELLU, // ie-Latn-EE
    0x69674E4745677970LLU, // ig-Egyp-NG
    0x69674E474C61746ELLU, // ig-Latn-NG
    0x6973495345677970LLU, // is-Egyp-IS
    0x697349534C61746ELLU, // is-Latn-IS
    0x6974495445677970LLU, // it-Egyp-IT
    0x697449544C61746ELLU, // it-Latn-IT
    0x6A614A5045677970LLU, // ja-Egyp-JP
    0x6A614A504A70616ELLU, // ja-Jpan-JP
    0x6A76494445677970LLU, // jv-Egyp-ID
    0x6A7649444C61746ELLU, // jv-Latn-ID
    0x6B61474545677970LLU, // ka-Egyp-GE
    0x6B61474547656F72LLU, // ka-Geor-GE
    0x808A435645677970LLU, // kea-Egyp-CV
    0x808A43564C61746ELLU, // kea-Latn-CV
    0xBCCA425245677970LLU, // kgp-Egyp-BR
    0xBCCA42524C61746ELLU, // kgp-Latn-BR
    0x6B6B4B5A4379726CLLU, // kk-Cyrl-KZ
    0x6B6B4B5A45677970LLU, // kk-Egyp-KZ
    0x6B6D4B4845677970LLU, // km-Egyp-KH
    0x6B6D4B484B686D72LLU, // km-Khmr-KH
    0x6B6E494E45677970LLU, // kn-Egyp-IN
    0x6B6E494E4B6E6461LLU, // kn-Knda-IN
    0x6B6F4B5245677970LLU, // ko-Egyp-KR
    0x6B6F4B524B6F7265LLU, // ko-Kore-KR
    0xA9CA494E44657661LLU, // kok-Deva-IN
    0xA9CA494E45677970LLU, // kok-Egyp-IN
    0x6B73494E41726162LLU, // ks-Arab-IN
    0x6B73494E44657661LLU, // ks-Deva-IN
    0x6B73494E45677970LLU, // ks-Egyp-IN
    0x6B75545245677970LLU, // ku-Egyp-TR
    0x6B7554524C61746ELLU, // ku-Latn-TR
    0xD6EA494E44657661LLU, // kxv-Deva-IN
    0xD6EA494E45677970LLU, // kxv-Egyp-IN
    0xD6EA494E4C61746ELLU, // kxv-Latn-IN
    0xD6EA494E4F727961LLU, // kxv-Orya-IN
    0xD6EA494E54656C75LLU, // kxv-Telu-IN
    0x6B794B474379726CLLU, // ky-Cyrl-KG
    0x6B794B4745677970LLU, // ky-Egyp-KG
    0x6C624C5545677970LLU, // lb-Egyp-LU
    0x6C624C554C61746ELLU, // lb-Latn-LU
    0xA50B495445677970LLU, // lij-Egyp-IT
    0xA50B49544C61746ELLU, // lij-Latn-IT
    0xB98B495445677970LLU, // lmo-Egyp-IT
    0xB98B49544C61746ELLU, // lmo-Latn-IT
    0x6C6F4C4145677970LLU, // lo-Egyp-LA
    0x6C6F4C414C616F6FLLU, // lo-Laoo-LA
    0x6C744C5445677970LLU, // lt-Egyp-LT
    0x6C744C544C61746ELLU, // lt-Latn-LT
    0x6C764C5645677970LLU, // lv-Egyp-LV
    0x6C764C564C61746ELLU, // lv-Latn-LV
    0xA00C494E44657661LLU, // mai-Deva-IN
    0xA00C494E45677970LLU, // mai-Egyp-IN
    0x6D694E5A45677970LLU, // mi-Egyp-NZ
    0x6D694E5A4C61746ELLU, // mi-Latn-NZ
    0x6D6B4D4B4379726CLLU, // mk-Cyrl-MK
    0x6D6B4D4B45677970LLU, // mk-Egyp-MK
    0x6D6C494E45677970LLU, // ml-Egyp-IN
    0x6D6C494E4D6C796DLLU, // ml-Mlym-IN
    0x6D6E4D4E4379726CLLU, // mn-Cyrl-MN
    0x6D6E4D4E45677970LLU, // mn-Egyp-MN
    0xA1AC494E42656E67LLU, // mni-Beng-IN
    0xA1AC494E45677970LLU, // mni-Egyp-IN
    0x6D72494E44657661LLU, // mr-Deva-IN
    0x6D72494E45677970LLU, // mr-Egyp-IN
    0x6D734D5945677970LLU, // ms-Egyp-MY
    0x6D734D594C61746ELLU, // ms-Latn-MY
    0x6D744D5445677970LLU, // mt-Egyp-MT
    0x6D744D544C61746ELLU, // mt-Latn-MT
    0x6D794D4D45677970LLU, // my-Egyp-MM
    0x6D794D4D4D796D72LLU, // my-Mymr-MM
    0x6E624E4F45677970LLU, // nb-Egyp-NO
    0x6E624E4F4C61746ELLU, // nb-Latn-NO
    0xC86D444545677970LLU, // nds-Egyp-DE
    0xC86D44454C61746ELLU, // nds-Latn-DE
    0x6E654E5044657661LLU, // ne-Deva-NP
    0x6E654E5045677970LLU, // ne-Egyp-NP
    0x6E6C4E4C45677970LLU, // nl-Egyp-NL
    0x6E6C4E4C4C61746ELLU, // nl-Latn-NL
    0x6E6E4E4F45677970LLU, // nn-Egyp-NO
    0x6E6E4E4F4C61746ELLU, // nn-Latn-NO
    0x6E6F4E4F45677970LLU, // no-Egyp-NO
    0x6E6F4E4F4C61746ELLU, // no-Latn-NO
    0xBA0D474E45677970LLU, // nqo-Egyp-GN
    0xBA0D474E4E6B6F6FLLU, // nqo-Nkoo-GN
    0x6F63465245677970LLU, // oc-Egyp-FR
    0x6F6346524C61746ELLU, // oc-Latn-FR
    0x6F72494E45677970LLU, // or-Egyp-IN
    0x6F72494E4F727961LLU, // or-Orya-IN
    0x7061494E45677970LLU, // pa-Egyp-IN
    0x7061494E47757275LLU, // pa-Guru-IN
    0xB04F4E4745677970LLU, // pcm-Egyp-NG
    0xB04F4E474C61746ELLU, // pcm-Latn-NG
    0x706C504C45677970LLU, // pl-Egyp-PL
    0x706C504C4C61746ELLU, // pl-Latn-PL
    0x9A2F504C45677970LLU, // prg-Egyp-PL
    0x9A2F504C4C61746ELLU, // prg-Latn-PL
    0x7073414641726162LLU, // ps-Arab-AF
    0x7073414645677970LLU, // ps-Egyp-AF
    0x7074425245677970LLU, // pt-Egyp-BR
    0x707442524C61746ELLU, // pt-Latn-BR
    0x7175504545677970LLU, // qu-Egyp-PE
    0x717550454C61746ELLU, // qu-Latn-PE
    0xA411494E44657661LLU, // raj-Deva-IN
    0xA411494E45677970LLU, // raj-Egyp-IN
    0x726D434845677970LLU, // rm-Egyp-CH
    0x726D43484C61746ELLU, // rm-Latn-CH
    0x726F524F45677970LLU, // ro-Egyp-RO
    0x726F524F4C61746ELLU, // ro-Latn-RO
    0x727552554379726CLLU, // ru-Cyrl-RU
    0x7275525545677970LLU, // ru-Egyp-RU
    0x7361494E44657661LLU, // sa-Deva-IN
    0x7361494E45677970LLU, // sa-Egyp-IN
    0x9C1252554379726CLLU, // sah-Cyrl-RU
    0x9C12525545677970LLU, // sah-Egyp-RU
    0xCC12494E45677970LLU, // sat-Egyp-IN
    0xCC12494E4F6C636BLLU, // sat-Olck-IN
    0x7363495445677970LLU, // sc-Egyp-IT
    0x736349544C61746ELLU, // sc-Latn-IT
    0x7364504B41726162LLU, // sd-Arab-PK
    0x7364494E44657661LLU, // sd-Deva-IN
    0x7364504B45677970LLU, // sd-Egyp-PK
    0x73694C4B45677970LLU, // si-Egyp-LK
    0x73694C4B53696E68LLU, // si-Sinh-LK
    0x736B534B45677970LLU, // sk-Egyp-SK
    0x736B534B4C61746ELLU, // sk-Latn-SK
    0x736C534945677970LLU, // sl-Egyp-SI
    0x736C53494C61746ELLU, // sl-Latn-SI
    0x736F534F45677970LLU, // so-Egyp-SO
    0x736F534F4C61746ELLU, // so-Latn-SO
    0x7371414C45677970LLU, // sq-Egyp-AL
    0x7371414C4C61746ELLU, // sq-Latn-AL
    0x737252534379726CLLU, // sr-Cyrl-RS
    0x7372525345677970LLU, // sr-Egyp-RS
    0x737252534C61746ELLU, // sr-Latn-RS
    0x7375494445677970LLU, // su-Egyp-ID
    0x737549444C61746ELLU, // su-Latn-ID
    0x7376534545677970LLU, // sv-Egyp-SE
    0x737653454C61746ELLU, // sv-Latn-SE
    0x7377545A45677970LLU, // sw-Egyp-TZ
    0x7377545A4C61746ELLU, // sw-Latn-TZ
    0xC712495145677970LLU, // syr-Egyp-IQ
    0xC712495153797263LLU, // syr-Syrc-IQ
    0xAF32504C45677970LLU, // szl-Egyp-PL
    0xAF32504C4C61746ELLU, // szl-Latn-PL
    0x7461494E45677970LLU, // ta-Egyp-IN
    0x7461494E54616D6CLLU, // ta-Taml-IN
    0x7465494E45677970LLU, // te-Egyp-IN
    0x7465494E54656C75LLU, // te-Telu-IN
    0x7467544A4379726CLLU, // tg-Cyrl-TJ
    0x7467544A45677970LLU, // tg-Egyp-TJ
    0x7468544845677970LLU, // th-Egyp-TH
    0x7468544854686169LLU, // th-Thai-TH
    0x7469455445677970LLU, // ti-Egyp-ET
    0x7469455445746869LLU, // ti-Ethi-ET
    0x746B544D45677970LLU, // tk-Egyp-TM
    0x746B544D4C61746ELLU, // tk-Latn-TM
    0x746F544F45677970LLU, // to-Egyp-TO
    0x746F544F4C61746ELLU, // to-Latn-TO
    0x7472545245677970LLU, // tr-Egyp-TR
    0x747254524C61746ELLU, // tr-Latn-TR
    0x747452554379726CLLU, // tt-Cyrl-RU
    0x7474525545677970LLU, // tt-Egyp-RU
    0x7567434E41726162LLU, // ug-Arab-CN
    0x7567434E45677970LLU, // ug-Egyp-CN
    0x756B55414379726CLLU, // uk-Cyrl-UA
    0x756B554145677970LLU, // uk-Egyp-UA
    0x7572504B41726162LLU, // ur-Arab-PK
    0x7572504B45677970LLU, // ur-Egyp-PK
    0x757A555A4379726CLLU, // uz-Cyrl-UZ
    0x757A555A45677970LLU, // uz-Egyp-UZ
    0x757A555A4C61746ELLU, // uz-Latn-UZ
    0x8895495445677970LLU, // vec-Egyp-IT
    0x889549544C61746ELLU, // vec-Latn-IT
    0x7669564E45677970LLU, // vi-Egyp-VN
    0x7669564E4C61746ELLU, // vi-Latn-VN
    0xD9954D5A45677970LLU, // vmw-Egyp-MZ
    0xD9954D5A4C61746ELLU, // vmw-Latn-MZ
    0x776F534E45677970LLU, // wo-Egyp-SN
    0x776F534E4C61746ELLU, // wo-Latn-SN
    0x78685A4145677970LLU, // xh-Egyp-ZA
    0x78685A414C61746ELLU, // xh-Latn-ZA
    0xC5B7494E44657661LLU, // xnr-Deva-IN
    0xC5B7494E45677970LLU, // xnr-Egyp-IN
    0x796F4E4745677970LLU, // yo-Egyp-NG
    0x796F4E474C61746ELLU, // yo-Latn-NG
    0xAE38425245677970LLU, // yrl-Egyp-BR
    0xAE3842524C61746ELLU, // yrl-Latn-BR
    0x9298484B45677970LLU, // yue-Egyp-HK
    0x9298434E48616E73LLU, // yue-Hans-CN
    0x9298484B48616E74LLU, // yue-Hant-HK
    0x7A61434E45677970LLU, // za-Egyp-CN
    0x7A61434E4C61746ELLU, // za-Latn-CN
    0x7A68434E45677970LLU, // zh-Egyp-CN
    0x7A68434E48616E73LLU, // zh-Hans-CN
    0x7A68545748616E74LLU, // zh-Hant-TW
    0x7A755A4145677970LLU, // zu-Egyp-ZA
    0x7A755A414C61746ELLU, // zu-Latn-ZA
});

const struct {
    const char script[4];
    const std::unordered_map<uint32_t, uint32_t>* map;
} SCRIPT_PARENTS[] = {
};

const size_t MAX_PARENT_DEPTH = 1;
