/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.server.compat.overrides;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import java.io.Closeable;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

//TODO(b/177999772): The Java XmlWriter code generation in xsdc seems to be broken.

/**
 * <p>
 * Writes an XML file containing per-change compat framework overrides.
 * </p>
 * <p>
 * Output example:
 * </p>
 *
 * <pre>
 * {@code
 * <overrides>
 *     <change-overrides changeId="111">
 *         <validated>
 *              <override-value packageName="foo.bar" enabled="true"/>
 *              <override-value packageName="bar.baz" enabled="false"/>
 *         </validated>
 *         <deferred>
 *              <override-value packageName="bar.foo" enabled="true"/>
 *         </deferred>
 *     </change-overrides>
 *     <change-overrides changeId="222">
 *         <validated>
 *         </validated>
 *         <deferred>
 *              <override-value packageName="bar.foo" enabled="true"/>
 *         </deferred>
 *     </change-overrides>
 * </overrides>
 *  }
 *
 * </pre>
 *
 */
public final class XmlWriter implements Closeable {
    private static final String XML_ROOT = "overrides";
    private static final String XML_CHANGE_OVERRIDES_ELEMENT = "change-overrides";
    private static final String XML_CHANGE_ID_ATTR = "changeId";
    private static final String XML_PACKAGENAME_ATTR = "packageName";
    private static final String XML_ENABLED_ATTR = "enabled";
    private static final String XML_VALIDATED_ELEMENT = "validated";
    private static final String XML_DEFERRED_ELEMENT = "deferred";
    private static final String XML_OVERRIDE_VALUE_ELEMENT = "override-value";

    private PrintWriter mOutput;

    public XmlWriter(PrintWriter printWriter) {
        mOutput = printWriter;
    }

    /**
     * This method is used to serialise a {@code Overrides} to XML.
     *
     * TODO(b/177999772): This method should be autogenerated.
     *
     * @param writer    XmlWriter to use for serialisation.
     * @param overrides The {@code Overrides} to be serialised.
     * @throws IOException
     */
    public static void write(XmlWriter writer, Overrides overrides) throws IOException {
        try {
            Document document = createDocument();
            Element root = createOverrides(document, overrides);
            document.appendChild(root);
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource domSource = new DOMSource(document);
            StreamResult result = new StreamResult(writer.mOutput);

            transformer.transform(domSource, result);
        } catch (TransformerException e) {
            throw new IOException("Failed to write output", e);
        }
    }

    @Override
    public void close() {
        mOutput.close();
    }

    private static Element createOverrides(Document document, Overrides overrides) {
        Element root = document.createElement(XML_ROOT);
        for (ChangeOverrides changeOverrides : overrides.getChangeOverrides()) {
            Element changeOverridesElement = createChangeOverrides(document, changeOverrides);
            root.appendChild(changeOverridesElement);
        }
        return root;
    }

    private static Element createChangeOverrides(Document document,
            ChangeOverrides changeOverrides) {
        Element changeOverridesElement = document.createElement(XML_CHANGE_OVERRIDES_ELEMENT);
        changeOverridesElement.setAttribute(XML_CHANGE_ID_ATTR,
                                            String.valueOf(changeOverrides.getChangeId()));
        changeOverridesElement.appendChild(createOverrideValueList(document, XML_DEFERRED_ELEMENT,
                                           changeOverrides.getDeferred().getOverrideValue()));
        changeOverridesElement.appendChild(createOverrideValueList(document, XML_VALIDATED_ELEMENT,
                                           changeOverrides.getValidated().getOverrideValue()));
        return changeOverridesElement;
    }

    private static Element createOverrideValueList(Document document, String tagName,
            List<OverrideValue> overrides) {
        Element overridesElement = document.createElement(tagName);
        for (OverrideValue overrideValue : overrides) {
            overridesElement.appendChild(createOverride(document, overrideValue));
        }
        return overridesElement;
    }

    private static Element createOverride(Document document, OverrideValue overrideValue) {
        Element overrideElement = document.createElement(XML_OVERRIDE_VALUE_ELEMENT);
        overrideElement.setAttribute(XML_PACKAGENAME_ATTR, overrideValue.getPackageName());
        overrideElement.setAttribute(XML_ENABLED_ATTR, String.valueOf(overrideValue.getEnabled()));
        return overrideElement;
    }

    private static Document createDocument() {
        try {
            DocumentBuilderFactory documentFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = documentFactory.newDocumentBuilder();
            return documentBuilder.newDocument();
        } catch (ParserConfigurationException e) {
            throw new RuntimeException("Failed to create a new document", e);
        }
    }
}
