/*
 * Copyright (C) 2010 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.server;

import android.app.AlarmManager;
import android.app.PendingIntent;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.content.pm.PackageManager.NameNotFoundException;
import android.os.Binder;
import android.os.DropBoxManager;
import android.os.SystemClock;
import android.util.Slog;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileDescriptor;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Random;

/**
 * Sampling profile service for controlling the saving of profile data generated by platform
 * directly to dropbox manager. The service will not upload any data if the sampling profiler
 * is not enabled.
 */
public class SamplingProfilerService extends Binder {
    private static final String TAG = "SamplingProfilerService";

    private static final boolean LOCAL_LOGV = false;
    private static final char[] hexDigits = "0123456789abcdef".toCharArray();
    private static final long MAX_UPLOAD_SIZE = 4096; // Maximum upload size in byte.
    // Wake up the service every 24 hours to check new profile files.
    private static final long WAKE_INTERVAL = AlarmManager.INTERVAL_DAY;
    private static final String UPLOAD_PROFILE_ACTION = "android.app.profiler.intent.UPLOAD";
    private static final String ART_PROFILES_DIR = "/data/dalvik-cache/profiles";

    private final Context mContext;
    private BroadcastReceiver mUploadProfileReceiver;

    public SamplingProfilerService(Context context) {
        mContext = context;
        startWorking(context);
    }

    private class UploadProfileReceiver extends BroadcastReceiver {
        public void onReceive(Context context, Intent intent) {
            if (UPLOAD_PROFILE_ACTION.equals(intent.getAction())) {
                startUploadTask();
            }
        }
    }

    // Upload profile entries to dropbox manager.
    private void startUploadTask() {
        final DropBoxManager dropbox =
            (DropBoxManager) mContext.getSystemService(Context.DROPBOX_SERVICE);
        Random random = new Random(SystemClock.elapsedRealtime());
        // List of non-empty profile files.
        ArrayList<File> mProfileFileList = new ArrayList<File>();
        long spaceLeft = MAX_UPLOAD_SIZE;

        File[] artFiles = new File(ART_PROFILES_DIR).listFiles();
        for (int i = 0; artFiles != null && i < artFiles.length; i++) {
            long fileSize = artFiles[i].length();
            if (fileSize > 0 && !artFiles[i].getName().endsWith("@old")) {
                mProfileFileList.add(artFiles[i]);
            }
        }

        // Randomly pick a non-empty profile file and read the file content.
        while (mProfileFileList.size() > 0 && spaceLeft > 0) {
            int listLength = mProfileFileList.size();
            int index = random.nextInt(listLength);
            long dumpSpace = handleARTFile(mProfileFileList.get(index), dropbox,
                    random, spaceLeft);
            spaceLeft -= dumpSpace;
            mProfileFileList.remove(index);
        }
    }

    private void startWorking(Context context) {
        if (LOCAL_LOGV) Slog.v(TAG, "starting SamplingProfilerService!");

        final DropBoxManager dropbox =
                (DropBoxManager) context.getSystemService(Context.DROPBOX_SERVICE);

        mUploadProfileReceiver = new UploadProfileReceiver();
        IntentFilter filter = new IntentFilter();
        filter.addAction(UPLOAD_PROFILE_ACTION);
        context.registerReceiver(mUploadProfileReceiver, filter);

        Intent uploadIntent = new Intent(UPLOAD_PROFILE_ACTION);
        PendingIntent uploadPendingIntent =
            PendingIntent.getBroadcast(context, 0, uploadIntent, 0);
        AlarmManager alarmManager =
            (AlarmManager) context.getSystemService(Context.ALARM_SERVICE);
        // We start the first run of the service immediately and repeat waking
        // up the service every day.
        alarmManager.setInexactRepeating(AlarmManager.RTC_WAKEUP,
                System.currentTimeMillis(), WAKE_INTERVAL, uploadPendingIntent);

        if (LOCAL_LOGV) Slog.v(TAG, "SamplingProfilerService activated");
    }

    /*
     * Check if we can add entries in the file into dropbox within the space limit.
     * @return The space quota used by this file.
     */
    private long handleARTFile(File file, DropBoxManager dropbox, Random random,
            long spaceLeft) {
        long fileSize = file.length();
        String apkSHA256 = apkHash256(file.getName());
        ArrayList<String> fileContent = readProfileFile(file);
        String dumpContent = "";
        long dumpSize = apkSHA256.length() + 1;

        // Randomly pick entries from the current profile file and check if we
        // still have enough space to write the entry out.
        while (fileContent.size() > 0) {
            int index = random.nextInt(fileContent.size());
            String entry = fileContent.get(index);
            if (dumpSize + entry.length() < spaceLeft) {
                dumpContent += entry + "\n";
                dumpSize += entry.length() + 1;
            }
            fileContent.remove(index);
        }

        if (dumpSize > apkSHA256.length() + 1) {
            // Because some entries are added into the dump content,
            // we add it to dropbox with the app's digest.
            dumpContent = apkSHA256 + "\n" + dumpContent;
            dropbox.addText(TAG, dumpContent);
            // Clear the processed profile file to avoid sending
            // the same entries again.
            try {
                new RandomAccessFile(file, "rw").setLength(0);
            } catch (IOException e) {
            }
            return dumpSize;
        } else {
            // No entry is added. We still keep the profile file.
            return 0;
        }
    }

    /*
     * Read the content of the profile file. The first line is the summary, and
     * each line in the file contains a single profile entry.
     */
    private static ArrayList<String> readProfileFile(File file) {
        ArrayList<String> entryList = new ArrayList();
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new FileReader(file));
            String line;
            // skip the first line, which contains summary info
            line = reader.readLine();
            while ((line = reader.readLine()) != null) {
                entryList.add(line);
            }
        } catch (IOException e) {
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException e) {}
            }
        }
        return entryList;
    }

    // Compute the digest of an app given package name.
    private String apkHash256(String packageName) {
        File app = null;
        try {
            PackageManager packageManager = mContext.getPackageManager();
            ApplicationInfo applicationInfo =
                packageManager.getApplicationInfo(packageName, 0);
            app = new File(applicationInfo.sourceDir);
        } catch (NameNotFoundException e) {
            return "";
        }

        MessageDigest digester = null;
        try {
            digester = MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            return "";
        }

        InputStream inputStream = null;
        try {
            inputStream = new FileInputStream(app);

            // Read bytes off of the stream until its done.
            int bytesRead;
            byte[] buf = new byte[1024];
            while ((bytesRead = inputStream.read(buf)) > 0) {
                digester.update(buf, 0, bytesRead);
            }
        } catch (IOException e) {
            return "";
        } finally {
            if (inputStream != null) {
                try {
                    inputStream.close();
                } catch (IOException e) {}
            }
        }

        return toHex(digester.digest());
    }

    // Convert byte array into hex string.
    private static String toHex(byte[] input) {
        StringBuilder sb = new StringBuilder(2 * input.length);
        for (byte b : input) {
            sb.append(hexDigits[(b >> 4) & 0xf]).append(hexDigits[b & 0xf]);
        }
        return sb.toString();
    }

    @Override
    protected void dump(FileDescriptor fd, PrintWriter pw, String[] args) {
        mContext.enforceCallingOrSelfPermission(android.Manifest.permission.DUMP, TAG);

        pw.println("SamplingProfilerService:");
        pw.println("Watching directory: " + ART_PROFILES_DIR);
    }
}
