package android.security;

import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.spec.AlgorithmParameterSpec;

import javax.crypto.Mac;
import javax.crypto.MacSpi;

/**
 * TODO: Insert description here. (generated by klyubin)
 *
 * @hide
 */
public abstract class KeyStoreMacSpi extends MacSpi {

    private final String mAlgorithm;

    private Mac mDelegate;

    public static class HmacSHA256 extends KeyStoreMacSpi {
        public HmacSHA256() {
            super("HmacSHA256");
        }
    }

    protected KeyStoreMacSpi(String algorithm) {
        mAlgorithm = algorithm;
    }

    private String getAlgorithm() {
        return mAlgorithm;
    }

    private Mac getDelegate() {
        if (mDelegate == null) {
            try {
                mDelegate = Mac.getInstance(getAlgorithm(), "AndroidOpenSSL");
            } catch (Exception e) {
                throw new RuntimeException(
                        "Failed to get Mac " + getAlgorithm() + " from Conscrypt", e);
            }
        }
        return mDelegate;
    }

    @Override
    protected void engineInit(Key key, AlgorithmParameterSpec params) throws InvalidKeyException,
            InvalidAlgorithmParameterException {
        if (!(key instanceof DelegatedSecretKey)) {
            throw new InvalidKeyException(
                    "Unsupported key: " + ((key != null) ? key.getClass().getName() : "null"));
        }
        getDelegate().init(((DelegatedSecretKey) key).getDelegate(), params);
    }

    @Override
    protected byte[] engineDoFinal() {
        return getDelegate().doFinal();
    }

    @Override
    protected int engineGetMacLength() {
        return getDelegate().getMacLength();
    }

    @Override
    protected void engineReset() {
        getDelegate().reset();
    }

    @Override
    protected void engineUpdate(byte input) {
        getDelegate().update(input);
    }

    @Override
    protected void engineUpdate(byte[] input, int offset, int len) {
        getDelegate().update(input, offset, len);
    }
}
