/*
 * Copyright (C) 2006 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.telephony;

import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.telephony.Rlog;

//TODO: Complete description
/**
 * Contains precise call state and call fail causes generated by the
 * framework and the RIL.
 *
 * The following call information is included in returned PreciseCallState:
 *
 * <ul>
 *   <li>Ringing call state.
 *   <li>Foreground call state.
 *   <li>Background call state.
 *   <li>Disconnect cause; generated by the framework.
 *   <li>Precise disconnect cause; generated by the RIL.
 * </ul>
 */
public class PreciseCallState implements Parcelable {

    static final String LOG_TAG = "PreciseCallState";
    private static final boolean DBG = true;

    /** Call state is not valid (Not received a call state). */
    public static final int PRECISE_CALL_STATE_NOT_VALID =      -1;
    /** Call state: No activity. */
    public static final int PRECISE_CALL_STATE_IDLE =           0;
    /** Call state: Active. */
    public static final int PRECISE_CALL_STATE_ACTIVE =         1;
    /** Call state: On hold. */
    public static final int PRECISE_CALL_STATE_HOLDING =        2;
    /** Call state: Dialing. */
    public static final int PRECISE_CALL_STATE_DIALING =        3;
    /** Call state: Alerting. */
    public static final int PRECISE_CALL_STATE_ALERTING =       4;
    /** Call state: Incoming. */
    public static final int PRECISE_CALL_STATE_INCOMING =       5;
    /** Call state: Waiting. */
    public static final int PRECISE_CALL_STATE_WAITING =        6;
    /** Call state: Disconnected. */
    public static final int PRECISE_CALL_STATE_DISCONNECTED =   7;
    /** Call state: Disconnecting. */
    public static final int PRECISE_CALL_STATE_DISCONNECTING =  8;

    /** The disconnect cause is not valid (Not received a disconnect cause) */
    public static final int DISCONNECT_CAUSE_NOT_VALID                      = -1;
    /** Has not yet disconnected */
    public static final int DISCONNECT_CAUSE_NOT_DISCONNECTED               = 0;
    /** An incoming call that was missed and never answered */
    public static final int DISCONNECT_CAUSE_INCOMING_MISSED                = 1;
    /** Normal; Remote hangup*/
    public static final int DISCONNECT_CAUSE_NORMAL                         = 2;
    /** Normal; Local hangup */
    public static final int DISCONNECT_CAUSE_LOCAL                          = 3;
    /** Outgoing call to busy line */
    public static final int DISCONNECT_CAUSE_BUSY                           = 4;
    /** Outgoing call to congested network */
    public static final int DISCONNECT_CAUSE_CONGESTION                     = 5;
    /** Not presently used */
    public static final int DISCONNECT_CAUSE_MMI                            = 6;
    /** Invalid dial string */
    public static final int DISCONNECT_CAUSE_INVALID_NUMBER                 = 7;
    /** Cannot reach the peer */
    public static final int DISCONNECT_CAUSE_NUMBER_UNREACHABLE             = 8;
    /** Cannot reach the server */
    public static final int DISCONNECT_CAUSE_SERVER_UNREACHABLE             = 9;
    /** Invalid credentials */
    public static final int DISCONNECT_CAUSE_INVALID_CREDENTIALS            = 10;
    /** Calling from out of network is not allowed */
    public static final int DISCONNECT_CAUSE_OUT_OF_NETWORK                 = 11;
    /** Server error */
    public static final int DISCONNECT_CAUSE_SERVER_ERROR                   = 12;
    /** Client timed out */
    public static final int DISCONNECT_CAUSE_TIMED_OUT                      = 13;
    /** Client went out of network range */
    public static final int DISCONNECT_CAUSE_LOST_SIGNAL                    = 14;
    /** GSM or CDMA ACM limit exceeded */
    public static final int DISCONNECT_CAUSE_LIMIT_EXCEEDED                 = 15;
    /** An incoming call that was rejected */
    public static final int DISCONNECT_CAUSE_INCOMING_REJECTED              = 16;
    /** Radio is turned off explicitly */
    public static final int DISCONNECT_CAUSE_POWER_OFF                      = 17;
    /** Out of service */
    public static final int DISCONNECT_CAUSE_OUT_OF_SERVICE                 = 18;
    /** No ICC, ICC locked, or other ICC error */
    public static final int DISCONNECT_CAUSE_ICC_ERROR                      = 19;
    /** Call was blocked by call barring */
    public static final int DISCONNECT_CAUSE_CALL_BARRED                    = 20;
    /** Call was blocked by fixed dial number */
    public static final int DISCONNECT_CAUSE_FDN_BLOCKED                    = 21;
    /** Call was blocked by restricted all voice access */
    public static final int DISCONNECT_CAUSE_CS_RESTRICTED                  = 22;
    /** Call was blocked by restricted normal voice access */
    public static final int DISCONNECT_CAUSE_CS_RESTRICTED_NORMAL           = 23;
    /** Call was blocked by restricted emergency voice access */
    public static final int DISCONNECT_CAUSE_CS_RESTRICTED_EMERGENCY        = 24;
    /** Unassigned number */
    public static final int DISCONNECT_CAUSE_UNOBTAINABLE_NUMBER            = 25;
    /** MS is locked until next power cycle */
    public static final int DISCONNECT_CAUSE_CDMA_LOCKED_UNTIL_POWER_CYCLE  = 26;
    /** */
    public static final int DISCONNECT_CAUSE_CDMA_DROP                      = 27;
    /** INTERCEPT order received, MS state idle entered */
    public static final int DISCONNECT_CAUSE_CDMA_INTERCEPT                 = 28;
    /** MS has been redirected, call is cancelled */
    public static final int DISCONNECT_CAUSE_CDMA_REORDER                   = 29;
    /** Service option rejection */
    public static final int DISCONNECT_CAUSE_CDMA_SO_REJECT                 = 30;
    /** Requested service is rejected, retry delay is set */
    public static final int DISCONNECT_CAUSE_CDMA_RETRY_ORDER               = 31;
    /** */
    public static final int DISCONNECT_CAUSE_CDMA_ACCESS_FAILURE            = 32;
    /** */
    public static final int DISCONNECT_CAUSE_CDMA_PREEMPTED                 = 33;
    /** Not an emergency call */
    public static final int DISCONNECT_CAUSE_CDMA_NOT_EMERGENCY             = 34;
    /** Access Blocked by CDMA network */
    public static final int DISCONNECT_CAUSE_CDMA_ACCESS_BLOCKED            = 35;
    /** Unknown error or not specified */
    public static final int DISCONNECT_CAUSE_ERROR_UNSPECIFIED              = 36;

    /* Codes obtained from ril.h RIL_LastCallFailCause and CallFailCause
     * TODO: Complete Javadoc with TS 24.008 causes */
    /** The disconnect cause is not valid (Not received a disconnect cause)*/
    public static final int PRECISE_DISCONNECT_CAUSE_NOT_VALID                      = -1;
    /** No disconnect cause provided. Generally a local disconnect or an incoming missed call */
    public static final int PRECISE_DISCONNECT_CAUSE_NO_DISCONNECT_CAUSE_AVAILABLE  = 0;
    /** The destination cannot be reached because the number, although valid, is not currently assigned */
    public static final int PRECISE_DISCONNECT_CAUSE_UNOBTAINABLE_NUMBER            = 1;
    /** One of the users involved in the call has requested that the call is cleared */
    public static final int PRECISE_DISCONNECT_CAUSE_NORMAL                         = 16;
    /** The called user is unable to accept another call */
    public static final int PRECISE_DISCONNECT_CAUSE_BUSY                           = 17;
    /** The called number is no longer assigned */
    public static final int PRECISE_DISCONNECT_CAUSE_NUMBER_CHANGED                 = 22;
    /** Provided in response to a STATUS ENQUIRY message */
    public static final int PRECISE_DISCONNECT_CAUSE_STATUS_ENQUIRY                 = 30;
    /** Reports a normal disconnect only when no other normal cause applies */
    public static final int PRECISE_DISCONNECT_CAUSE_NORMAL_UNSPECIFIED             = 31;
    /** There is no channel presently available to handle the call */
    public static final int PRECISE_DISCONNECT_CAUSE_NO_CIRCUIT_AVAIL               = 34;
    /** The network is not functioning correctly and the condition is not likely to last a long period of time */
    public static final int PRECISE_DISCONNECT_CAUSE_TEMPORARY_FAILURE              = 41;
    /** The switching equipment is experiencing a period of high traffic */
    public static final int PRECISE_DISCONNECT_CAUSE_SWITCHING_CONGESTION           = 42;
    /** The channel cannot be provided */
    public static final int PRECISE_DISCONNECT_CAUSE_CHANNEL_NOT_AVAIL              = 44;
    /** The requested quality of service (ITU-T X.213) cannot be provided */
    public static final int PRECISE_DISCONNECT_CAUSE_QOS_NOT_AVAIL                  = 49;
    /** The requested bearer capability is not available at this time */
    public static final int PRECISE_DISCONNECT_CAUSE_BEARER_NOT_AVAIL               = 58;
    /** The call clearing is due to ACM being greater than or equal to ACMmax */
    public static final int PRECISE_DISCONNECT_CAUSE_ACM_LIMIT_EXCEEDED             = 68;
    
    /* TODO: codes not present in TS 24.008 document */
    public static final int PRECISE_DISCONNECT_CAUSE_CALL_BARRED                    = 240;
    public static final int PRECISE_DISCONNECT_CAUSE_FDN_BLOCKED                    = 241;
    /** The given IMSI is not known at the VLR */
    /** TS 24.008 cause 4 */
    public static final int PRECISE_DISCONNECT_CAUSE_IMSI_UNKNOWN_IN_VLR            = 242;
    /** The network does not accept emergency call establishment using an IMEI or not accept attach procedure for emergency services using an IMEI */
    /** TS 24.008 cause 5 */
    public static final int PRECISE_DISCONNECT_CAUSE_IMEI_NOT_ACCEPTED              = 243;
    
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_LOCKED_UNTIL_POWER_CYCLE  = 1000;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_DROP                      = 1001;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_INTERCEPT                 = 1002;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_REORDER                   = 1003;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_SO_REJECT                 = 1004;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_RETRY_ORDER               = 1005;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_ACCESS_FAILURE            = 1006;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_PREEMPTED                 = 1007;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_NOT_EMERGENCY             = 1008;
    public static final int PRECISE_DISCONNECT_CAUSE_CDMA_ACCESS_BLOCKED            = 1009;
    /** Disconnected due to unspecified reasons */
    public static final int PRECISE_DISCONNECT_CAUSE_ERROR_UNSPECIFIED              = 0xffff;

    private int mRingingCallState = PRECISE_CALL_STATE_NOT_VALID;
    private int mForegroundCallState = PRECISE_CALL_STATE_NOT_VALID;
    private int mBackgroundCallState = PRECISE_CALL_STATE_NOT_VALID;
    private int mDisconnectCause = DISCONNECT_CAUSE_NOT_VALID;
    private int mPreciseDisconnectCause = PRECISE_DISCONNECT_CAUSE_NOT_VALID;

    /**
     * Constructor
     * 
     * @hide
     */
    public PreciseCallState(int ringingCall, int foregroundCall, int backgroundCall,
            int disconnectCause, int preciseDisconnectCause) {
        mRingingCallState = ringingCall;
        mForegroundCallState = foregroundCall;
        mBackgroundCallState = backgroundCall;
        mDisconnectCause = disconnectCause;
        mPreciseDisconnectCause = preciseDisconnectCause;
    }
    
    /**
     * Empty Constructor
     * 
     * @hide
     */
    public PreciseCallState() {
    }

    /**
     * Construct a PreciseCallState object from the given parcel.
     */
    private PreciseCallState(Parcel in) {
        mRingingCallState = in.readInt();
        mForegroundCallState = in.readInt();
        mBackgroundCallState = in.readInt();
        mDisconnectCause = in.readInt();
        mPreciseDisconnectCause = in.readInt();
    }

    /**
     * Get precise ringing call state
     * 
     * @see PreciseCallState#PRECISE_CALL_STATE_NOT_VALID
     * @see PreciseCallState#PRECISE_CALL_STATE_IDLE
     * @see PreciseCallState#PRECISE_CALL_STATE_ACTIVE
     * @see PreciseCallState#PRECISE_CALL_STATE_HOLDING
     * @see PreciseCallState#PRECISE_CALL_STATE_DIALING
     * @see PreciseCallState#PRECISE_CALL_STATE_ALERTING
     * @see PreciseCallState#PRECISE_CALL_STATE_INCOMING
     * @see PreciseCallState#PRECISE_CALL_STATE_WAITING
     * @see PreciseCallState#PRECISE_CALL_STATE_DISCONNECTED
     * @see PreciseCallState#PRECISE_CALL_STATE_DISCONNECTING
     */
    public int getRingingCallState() {
        return mRingingCallState;
    }

    /**
     * Get precise foreground call state
     * 
     * @see PreciseCallState#PRECISE_CALL_STATE_NOT_VALID
     * @see PreciseCallState#PRECISE_CALL_STATE_IDLE
     * @see PreciseCallState#PRECISE_CALL_STATE_ACTIVE
     * @see PreciseCallState#PRECISE_CALL_STATE_HOLDING
     * @see PreciseCallState#PRECISE_CALL_STATE_DIALING
     * @see PreciseCallState#PRECISE_CALL_STATE_ALERTING
     * @see PreciseCallState#PRECISE_CALL_STATE_INCOMING
     * @see PreciseCallState#PRECISE_CALL_STATE_WAITING
     * @see PreciseCallState#PRECISE_CALL_STATE_DISCONNECTED
     * @see PreciseCallState#PRECISE_CALL_STATE_DISCONNECTING
     */
    public int getForegroundCallState() {
        return mForegroundCallState;
    }

    /**
     * Get precise background call state
     * 
     * @see PreciseCallState#PRECISE_CALL_STATE_NOT_VALID
     * @see PreciseCallState#PRECISE_CALL_STATE_IDLE
     * @see PreciseCallState#PRECISE_CALL_STATE_ACTIVE
     * @see PreciseCallState#PRECISE_CALL_STATE_HOLDING
     * @see PreciseCallState#PRECISE_CALL_STATE_DIALING
     * @see PreciseCallState#PRECISE_CALL_STATE_ALERTING
     * @see PreciseCallState#PRECISE_CALL_STATE_INCOMING
     * @see PreciseCallState#PRECISE_CALL_STATE_WAITING
     * @see PreciseCallState#PRECISE_CALL_STATE_DISCONNECTED
     * @see PreciseCallState#PRECISE_CALL_STATE_DISCONNECTING
     */
    public int getBackgroundCallState() {
        return mBackgroundCallState;
    }

    /**
     * Get disconnect cause generated by the framework
     * 
     * @see DISCONNECT_CAUSE_NOT_VALID
     * @see DISCONNECT_CAUSE_NOT_DISCONNECTED
     * @see DISCONNECT_CAUSE_INCOMING_MISSED
     * @see DISCONNECT_CAUSE_NORMAL
     * @see DISCONNECT_CAUSE_LOCAL
     * @see DISCONNECT_CAUSE_BUSY
     * @see DISCONNECT_CAUSE_CONGESTION
     * @see DISCONNECT_CAUSE_MMI
     * @see DISCONNECT_CAUSE_INVALID_NUMBER
     * @see DISCONNECT_CAUSE_NUMBER_UNREACHABLE
     * @see DISCONNECT_CAUSE_SERVER_UNREACHABLE
     * @see DISCONNECT_CAUSE_INVALID_CREDENTIALS
     * @see DISCONNECT_CAUSE_OUT_OF_NETWORK
     * @see DISCONNECT_CAUSE_SERVER_ERROR
     * @see DISCONNECT_CAUSE_TIMED_OUT
     * @see DISCONNECT_CAUSE_LOST_SIGNAL
     * @see DISCONNECT_CAUSE_LIMIT_EXCEEDED
     * @see DISCONNECT_CAUSE_INCOMING_REJECTED
     * @see DISCONNECT_CAUSE_POWER_OFF
     * @see DISCONNECT_CAUSE_OUT_OF_SERVICE
     * @see DISCONNECT_CAUSE_ICC_ERROR
     * @see DISCONNECT_CAUSE_CALL_BARRED
     * @see DISCONNECT_CAUSE_FDN_BLOCKED
     * @see DISCONNECT_CAUSE_CS_RESTRICTED
     * @see DISCONNECT_CAUSE_CS_RESTRICTED_NORMAL
     * @see DISCONNECT_CAUSE_CS_RESTRICTED_EMERGENCY
     * @see DISCONNECT_CAUSE_UNOBTAINABLE_NUMBER
     * @see DISCONNECT_CAUSE_CDMA_LOCKED_UNTIL_POWER_CYCLE
     * @see DISCONNECT_CAUSE_CDMA_DROP
     * @see DISCONNECT_CAUSE_CDMA_INTERCEPT
     * @see DISCONNECT_CAUSE_CDMA_REORDER
     * @see DISCONNECT_CAUSE_CDMA_SO_REJECT
     * @see DISCONNECT_CAUSE_CDMA_RETRY_ORDER
     * @see DISCONNECT_CAUSE_CDMA_ACCESS_FAILURE
     * @see DISCONNECT_CAUSE_CDMA_PREEMPTED
     * @see DISCONNECT_CAUSE_CDMA_NOT_EMERGENCY
     * @see DISCONNECT_CAUSE_CDMA_ACCESS_BLOCKED
     * @see DISCONNECT_CAUSE_ERROR_UNSPECIFIED
     */
    public int getDisconnectCause() {
        return mDisconnectCause;
    }

    /**
     * Get disconnect cause generated by the RIL
     * 
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_NOT_VALID
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_NO_DISCONNECT_CAUSE_AVAILABLE
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_UNOBTAINABLE_NUMBER
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_NORMAL
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_BUSY
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_NUMBER_CHANGED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_STATUS_ENQUIRY
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_NORMAL_UNSPECIFIED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_NO_CIRCUIT_AVAIL
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_TEMPORARY_FAILURE
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_SWITCHING_CONGESTION
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CHANNEL_NOT_AVAIL
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_QOS_NOT_AVAIL
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_BEARER_NOT_AVAIL
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_ACM_LIMIT_EXCEEDED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CALL_BARRED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_FDN_BLOCKED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_IMSI_UNKNOWN_IN_VLR
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_IMEI_NOT_ACCEPTED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_LOCKED_UNTIL_POWER_CYCLE
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_DROP
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_INTERCEPT
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_REORDER
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_SO_REJECT
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_RETRY_ORDER
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_ACCESS_FAILURE
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_PREEMPTED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_NOT_EMERGENCY
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_CDMA_ACCESS_BLOCKED
     * @see PreciseCallState#PRECISE_DISCONNECT_CAUSE_ERROR_UNSPECIFIED
     */
    public int getPreciseDisconnectCause() {
        return mPreciseDisconnectCause;
    }

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(Parcel out, int flags) {
        out.writeInt(mRingingCallState);
        out.writeInt(mForegroundCallState);
        out.writeInt(mBackgroundCallState);
        out.writeInt(mDisconnectCause);
        out.writeInt(mPreciseDisconnectCause);
    }

    public static final Parcelable.Creator<PreciseCallState> CREATOR = new Parcelable.Creator<PreciseCallState>() {

        public PreciseCallState createFromParcel(Parcel in) {
            return new PreciseCallState(in);
        }

        public PreciseCallState[] newArray(int size) {
            return new PreciseCallState[size];
        }
    };

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + mRingingCallState;
        result = prime * result + mForegroundCallState;
        result = prime * result + mBackgroundCallState;
        result = prime * result + mDisconnectCause;
        result = prime * result + mPreciseDisconnectCause;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PreciseCallState other = (PreciseCallState) obj;
        if (mRingingCallState != other.mRingingCallState)
            return false;
        if (mForegroundCallState != other.mForegroundCallState)
            return false;
        if (mBackgroundCallState != other.mBackgroundCallState)
            return false;
        if (mDisconnectCause != other.mDisconnectCause)
            return false;
        if (mPreciseDisconnectCause != other.mPreciseDisconnectCause)
            return false;
        return true;
    }

    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();

        sb.append("Ringing call state: " + mRingingCallState);
        sb.append(", Foreground call state: " + mForegroundCallState);
        sb.append(", Background call state: " + mBackgroundCallState);
        sb.append(", Disconnect cause: " + mDisconnectCause);
        sb.append(", Precise disconnect cause: " + mPreciseDisconnectCause);

        return sb.toString();
    }
}
