#!/usr/bin/env python3
#
# Copyright (C) 2022 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

'''
This script will create overlay configuration files that can be used
as a starting point for converting an existing system to use overlay
configuration files.

The input to this script is the dump generated by:
    adb shell cmd overlay dump
'''

import argparse
import logging
import os
import sys

def should_ignore(package):
    ''' Check if a package should be excluded from configuration file

    Package should be excluded if it is fabricated or it is listed for a secondary user, to
    avoid duplicates.'''

    if "mIsFabricated" in package and package["mIsFabricated"] == "true":
        logging.debug("%s is fabricated, ignoring", package["mPackageName"])
        return True
    if "mUserId" in package and package["mUserId"] > 0:
        logging.debug("%s is for user %d, ignoring", package["mPackageName"], package["mUserId"])
        return True
    return False

def parse_package_done(package, packages):
    ''' Parsing of current package is done, set as complete '''

    packages[package["mPackageName"]] = package

def parse_parameters(line, package):
    ''' Parse a parameter for a package, add to to current package '''

    key, value = line.split(':', 1)
    key = key.rstrip(".").strip()
    value = value.strip()
    if key in ["mPackageName", "mBaseCodePath", "mIsEnabled", "mIsMutable", "mIsFabricated"]:
        package[key] = value
    elif key in ["mPriority", "mUserId"]:
        package[key] = int(value)


def parse_dump_output(dump_name):
    ''' Parse an rro dump file into a dictionary '''

    packages = {}
    with open(dump_name) as file_dump:
        current_package = {}
        while True:
            line = file_dump.readline().strip()
            if line.startswith("IDMAP OF"):
                logging.debug("idmap section detected, work done")
                break
            if line.endswith('{'):
                logging.debug("new section detected")
                continue
            if line == '}':
                logging.debug("section ended")
                parse_package_done(current_package, packages)
                current_package = {}
                continue
            parse_parameters(line, current_package)

    return packages

def write_configurations(packages):
    ''' Generate the RRO config files from the parsed data.

    One configuration file will be created for each partition. '''

    partitions = {}
    for package in packages:
        if should_ignore(packages[package]):
            logging.debug("Ignoring package")
            continue
        partition = packages[package]["mBaseCodePath"].split('/')[1]
        if partition.strip() == "":
            logging.error("Parsed partition that is empty string")
            sys.exit()
        if partition not in partitions:
            partitions[partition] = []
        partitions[partition].append(package)

    if "data" in partitions:
        logging.error("Non fabricated RRO on data partition, this is likely an error, aborting")
        sys.exit()

    for partition in partitions:
        out_path = "./" + partition + "/overlay/config/config.xml"
        if not os.path.exists(os.path.dirname(out_path)):
            os.makedirs(os.path.dirname(out_path))
        with open(out_path, "wt") as file_config:
            file_config.write("<config>\n")
            for overlay in sorted(partitions[partition], key=lambda k: packages[k]['mPriority']):
                logging.debug(overlay)
                if should_ignore(packages[overlay]):
                    logging.debug("Ignoring package")
                else:
                    file_config.write('<overlay package="%s" enabled="%s" mutable="%s" />\n' %
                                      (packages[overlay]["mPackageName"],
                                       packages[overlay]["mIsEnabled"],
                                       packages[overlay]["mIsMutable"]))
            file_config.write("</config>\n")

def main():
    ''' Main method '''

    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--dump-file', required=True,
                        help=('File containing the output of '
                              '"adb shell cmd overlay dump"'))
    parser.add_argument("-l", "--log", dest="logLevel", choices=['DEBUG', 'INFO', 'WARNING',
                                                                 'ERROR', 'CRITICAL'],
                        default="INFO", help="Set the logging level")
    args = parser.parse_args()

    logging.basicConfig(level=getattr(logging, args.logLevel),
                        format='%(asctime)s %(levelname)s: %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')

    write_configurations(parse_dump_output(args.dump_file))

if __name__ == "__main__":
    main()
