package android.security;

/**
 * TODO: Insert description here. (generated by klyubin)
 */
public class Aes128CbcPkcs7PaddingKeyStoreCipherTest
        extends KeyStoreUnauthenticatedBlockCipherTestBase {
    private static final byte[] KAT_KEY = HexEncoding.decode("F16E698472578E919D92806262C5169F");
    private static final byte[] KAT_IV = HexEncoding.decode("EF743540F8421ACA128A3247521F3E7D");
    private static final byte[] KAT_PLAINTEXT = HexEncoding.decode(
            "5BEBF33569D90BF5E853814E12E7C7AA5758013F755773E29F4A25EC26EEB765F7F2DC251F7DC62AEFCA" +
            "1E8A5A11A1DCD44F0BD8FB593A5AE3");
    private static final byte[] KAT_CIPHERTEXT = HexEncoding.decode(
            "3197CF6DB9466188B5FED375329324EE7D6092A8C0E41DFAF49E3724271427896D56A6243C0D59D66397" +
            "22AF93CD53449BDDABF9C5F153EBDBFED9ED98C8CC37");

    @Override
    protected String getTransformation() {
        return "AES/CBC/PKCS7Padding";
    }

    @Override
    protected int getBlockSize() {
        return 16;
    }

    @Override
    protected byte[] getKatKey() {
        return KAT_KEY.clone();
    }

    @Override
    protected byte[] getKatIv() {
        return KAT_IV.clone();
    }

    @Override
    protected byte[] getKatPlaintext() {
        return KAT_PLAINTEXT.clone();
    }

    @Override
    protected byte[] getKatCiphertext() {
        return KAT_CIPHERTEXT.clone();
    }
}
