package android.security;

/**
 * TODO: Insert description here. (generated by klyubin)
 */
public class Aes128EcbNoPaddingKeyStoreCipherTest
        extends KeyStoreUnauthenticatedBlockCipherTestBase {

    private static final byte[] KAT_KEY = HexEncoding.decode("7DA2467F068854B3CB36E5C333A16619");
    private static final byte[] KAT_PLAINTEXT = HexEncoding.decode(
            "9A07C9575AD9CE209DF9F3953965CEBE8208587C7AE575A1904BF25048946D7B6168A9A27BCE554BEA94" +
            "EF26E6C742A0");
    private static final byte[] KAT_CIPHERTEXT = HexEncoding.decode(
            "8C47E49420FC92AC4CA2C601BC3F8AC31D01B260B7B849F2B8EEDFFFED8F36C31CBDA0D22F95C9C2A48C" +
            "347E8C77AC82");

    @Override
    protected String getTransformation() {
        return "AES/ECB/NoPadding";
    }

    @Override
    protected int getBlockSize() {
        return 16;
    }

    @Override
    protected byte[] getKatKey() {
        return KAT_KEY.clone();
    }

    @Override
    protected byte[] getKatIv() {
        return null;
    }

    @Override
    protected byte[] getKatPlaintext() {
        return KAT_PLAINTEXT.clone();
    }

    @Override
    protected byte[] getKatCiphertext() {
        return KAT_CIPHERTEXT.clone();
    }
}
