package android.security;

/**
 * TODO: Insert description here. (generated by klyubin)
 */
public class Aes128EcbPkcs7PaddingKeyStoreCipherTest
        extends KeyStoreUnauthenticatedBlockCipherTestBase {
    private static final byte[] KAT_KEY = HexEncoding.decode("C3BE04BCCB3D99B85290F113FE7AF194");
    private static final byte[] KAT_PLAINTEXT = HexEncoding.decode(
            "348C213FD8DF3F990C20C5ACBF07B34B6264AE245784A5A6176DBFB1C2E7DD27E52CC92B8EEE40614F05" +
            "B507B355F6354A2705BD86");
    private static final byte[] KAT_CIPHERTEXT = HexEncoding.decode(
            "07CD05C41FEDEDDC5DB4B3E35E676153184A119AA4DFDDC290616F1FA600931DE6BEA9BDB90D1D733899" +
            "946F8C8E5C0C4383F99F5D88E27F3EBC0C6E52759ED3");

    @Override
    protected String getTransformation() {
        return "AES/ECB/PKCS7Padding";
    }

    @Override
    protected int getBlockSize() {
        return 16;
    }

    @Override
    protected byte[] getKatKey() {
        return KAT_KEY.clone();
    }

    @Override
    protected byte[] getKatIv() {
        return null;
    }

    @Override
    protected byte[] getKatPlaintext() {
        return KAT_PLAINTEXT.clone();
    }

    @Override
    protected byte[] getKatCiphertext() {
        return KAT_CIPHERTEXT.clone();
    }
}
