package android.security;

import android.test.AndroidTestCase;
import android.util.Log;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;

/**
 * TODO: Insert description here. (generated by klyubin)
 */
public class KeyStoreAesCipherNistCavpKatTest extends AndroidTestCase {

    private static final String TAG = "KeyStoreAESKAT";

    public void testSomething() throws Exception {
        try (ZipInputStream zipIn = new ZipInputStream(
                getContext().getResources().getAssets().open("nist_cavp_aes_kat.zip"))) {
            ZipEntry zipEntry;
            while ((zipEntry = zipIn.getNextEntry()) != null) {
                String entryName = zipEntry.getName();
                if (!entryName.endsWith(".rsp")) {
                    continue;
                }

                if (zipEntry.getSize() > 1024 * 1024) {
                    fail("Entry " + entryName + " too large: " + zipEntry.getSize() + " bytes");
                }
                byte[] entryContents = new byte[(int) zipEntry.getSize()];
                readFully(zipIn, entryContents);
                runTestsForKatFile(entryName, entryContents);
            }
        }
    }

    private void runTestsForKatFile(String fileName, byte[] contents) throws Exception {
        if ((!fileName.endsWith(".rsp")) || (fileName.length() < 10)) {
            Log.i(TAG, "Ignoring " + fileName + " -- not a KAT file");
            return;
        }
        String mode = fileName.substring(0, 3);
        if ("CFB".equals(mode)) {
            mode = fileName.substring(0, 4);
        }
        try {
            Cipher.getInstance("AES/" + mode + "/NoPadding", AndroidKeyStoreProvider.PROVIDER_NAME);
        } catch (NoSuchAlgorithmException e) {
            Log.i(TAG, "Skipping " + fileName
                    + " -- transformation not supported by AndroidKeyStore");
            return;
        }

        try (BufferedReader in = new BufferedReader(new InputStreamReader(
                new ByteArrayInputStream(contents), "ISO-8859-1"))) {
            String line;
            int lineNumber = 0;
            String section = null; // ENCRYPT or DECRYPT

            boolean insideTestDefinition = false;
            int testNumber = 0;
            TestVector testVector = null;

            while ((line = in.readLine()) != null) {
                lineNumber++;
                line = line.trim();
                if (line.startsWith("#")) {
                    // Ignore comment lines
                    continue;
                }

                if (!insideTestDefinition) {
                    // Outside of a test definition
                    if (line.length() == 0) {
                        // Ignore empty lines
                        continue;
                    }
                    if ((line.startsWith("[")) && (line.endsWith("]"))) {
                        section = line.substring(1, line.length() - 1);
                        if ((!"DECRYPT".equals(section)) && (!"ENCRYPT".equals(section))) {
                            throw new IOException(lineNumber + ": Unexpected section: " + section);
                        }
                        continue;
                    }

                    // Check whether this is a NAME = VALUE line
                    int delimiterIndex = line.indexOf('=');
                    if (delimiterIndex == -1) {
                        throw new IOException(lineNumber + ": Unexpected line outside of test"
                                + " definition: " + line);
                    }
                    String name = line.substring(0, delimiterIndex).trim();
                    String value = line.substring(delimiterIndex + 1).trim();

                    if ("COUNT".equals(name)) {
                        testNumber = Integer.parseInt(value);
                        insideTestDefinition = true;
                        testVector = new TestVector();
                    } else {
                        throw new IOException(lineNumber + ": Unexpected line outside of test"
                                + " definition: " + line);
                    }
                } else {
                    // Inside of a test definition
                    if (line.length() == 0) {
                        // End of test definition
                        boolean encrypt;
                        if ("ENCRYPT".equals(section)) {
                            encrypt = true;
                        } else if ("DECRYPT".equals(section)) {
                            encrypt = false;
                        } else {
                            throw new IOException("Unexpected test operation: " + section);
                        }
                        Log.d(TAG, "Running test #" + testNumber + ": AES/" + mode + " from " + fileName);
                        runKatTest(mode, encrypt, testVector);
                        insideTestDefinition = false;
                        testVector = null;
                    } else {
                        // Check whether this is a NAME = VALUE line
                        int delimiterIndex = line.indexOf('=');
                        if (delimiterIndex == -1) {
                            throw new IOException(lineNumber + ": Unexpected line inside test"
                                    + " definition: " + line);
                        }
                        String name = line.substring(0, delimiterIndex).trim();
                        String value = line.substring(delimiterIndex + 1).trim();

                        if ("KEY".equals(name)) {
                            testVector.key = HexEncoding.decode(value);
                        } else if ("IV".equals(name)) {
                            testVector.iv = HexEncoding.decode(value);
                        } else if ("PLAINTEXT".equals(name)) {
                            testVector.plaintext = HexEncoding.decode(value);
                        } else if ("CIPHERTEXT".equals(name)) {
                            testVector.ciphertext = HexEncoding.decode(value);
                        } else {
                            throw new IOException(lineNumber + ": Unexpected line inside test"
                                    + " definition: " + line);
                        }
                    }
                }
            }
        }
    }

    private void runKatTest(String mode, boolean encrypt, TestVector testVector) throws Exception {
        SecretKey key =
                new DelegatedSecretKey("arbitrary", new SecretKeySpec(testVector.key, "AES"));
        Cipher cipher = Cipher.getInstance(
                "AES/" + mode + "/NoPadding", AndroidKeyStoreProvider.PROVIDER_NAME);

        int opmode = (encrypt) ? Cipher.ENCRYPT_MODE : Cipher.DECRYPT_MODE;
        if (testVector.iv != null) {
            cipher.init(opmode, key, new IvParameterSpec(testVector.iv));
        } else {
            cipher.init(opmode, key);
        }

        byte[] input = (encrypt) ? testVector.plaintext : testVector.ciphertext;
        byte[] actualOutput = cipher.doFinal(input);
        byte[] expectedOutput = (encrypt) ? testVector.ciphertext : testVector.plaintext;
        if (!Arrays.equals(expectedOutput, actualOutput)) {
            fail("Expected: " + HexEncoding.encode(expectedOutput)
                    + ", actual: " + HexEncoding.encode(actualOutput));
        }
    }

    private static void readFully(InputStream in, byte[] buf) throws IOException {
        int offset = 0;
        int remaining = buf.length;
        while (remaining > 0) {
            int chunkSize = in.read(buf, offset, remaining);
            if (chunkSize == -1) {
                throw new EOFException("Premature EOF. Remainig: " + remaining);
            }
            offset += chunkSize;
            remaining -= chunkSize;
        }
    }

    private static class TestVector {
        public byte[] key;
        public byte[] iv;
        public byte[] plaintext;
        public byte[] ciphertext;
    }
}
