//! JNI error handling types and helpers.
//!
//! Provides a typed error enum that maps to Java exceptions, plus the glue that
//! turns those errors into pending Java exceptions: [`ThrowJniError`], the
//! [`ErrorPolicy`] the generated native-method shims hand to
//! [`EnvOutcome::resolve`](jni::EnvOutcome::resolve). JNI methods should return
//! `Result<T, JniError>` so the generated shim applies that policy.

use jni::errors::{Error, ErrorPolicy, Result};
use jni::strings::{JNIStr, JNIString};
use jni::{jni_str, Env};
use std::any::Any;

/// Error type representing common Java exceptions that JNI methods may throw.
///
/// Each variant maps to a specific Java exception class. Return it as the `Err`
/// of a `#[jni_method]` and the generated shim throws the matching exception
/// via [`ThrowJniError`]; or throw it directly with [`throw_on`](Self::throw_on).
#[derive(Debug, thiserror::Error)]
pub enum JniError {
    /// java.lang.NullPointerException
    #[error("NullPointerException: {0}")]
    NullPointer(&'static str),
    /// java.lang.IllegalArgumentException
    #[error("IllegalArgumentException: {0}")]
    IllegalArgument(String),
    /// java.lang.RuntimeException
    #[error("RuntimeException: {0}")]
    Runtime(String),
    /// java.lang.OutOfMemoryError
    #[error("OutOfMemoryError")]
    OutOfMemory,
    /// java.lang.IllegalStateException
    #[error("IllegalStateException: {0}")]
    IllegalState(String),
    /// java.lang.UnsupportedOperationException
    #[error("UnsupportedOperationException: {0}")]
    UnsupportedOperation(String),
    /// java.lang.IndexOutOfBoundsException
    #[error("IndexOutOfBoundsException: {0}")]
    IndexOutOfBounds(String),
    /// java.lang.SecurityException
    #[error("SecurityException: {0}")]
    SecurityException(String),
    /// java.io.IOException
    #[error("IOException: {0}")]
    Io(String),
}

/// Errors surfaced by the `jni` crate map to `java.lang.RuntimeException`.
///
/// This makes `Result<T, jni::errors::Error>` usable as a `#[jni_method]`
/// return type: an `Err` becomes a pending RuntimeException. If the `jni`
/// error was caused by an already-pending Java exception, the original
/// exception is preserved (see [`ThrowJniError`]).
impl From<Error> for JniError {
    fn from(err: Error) -> Self {
        JniError::Runtime(err.to_string())
    }
}

impl JniError {
    /// The JNI class descriptor for this error's Java exception.
    ///
    /// Returned as a [`JNIStr`] so it can be passed straight to
    /// [`Env::throw_new`] with no per-throw allocation.
    pub fn exception_class(&self) -> &'static JNIStr {
        match self {
            JniError::NullPointer(_) => jni_str!("java/lang/NullPointerException"),
            JniError::IllegalArgument(_) => jni_str!("java/lang/IllegalArgumentException"),
            JniError::Runtime(_) => jni_str!("java/lang/RuntimeException"),
            JniError::OutOfMemory => jni_str!("java/lang/OutOfMemoryError"),
            JniError::IllegalState(_) => jni_str!("java/lang/IllegalStateException"),
            JniError::UnsupportedOperation(_) => {
                jni_str!("java/lang/UnsupportedOperationException")
            }
            JniError::IndexOutOfBounds(_) => jni_str!("java/lang/IndexOutOfBoundsException"),
            JniError::SecurityException(_) => jni_str!("java/lang/SecurityException"),
            JniError::Io(_) => jni_str!("java/io/IOException"),
        }
    }

    /// Returns the error message string.
    pub fn message(&self) -> String {
        match self {
            JniError::NullPointer(msg) => msg.to_string(),
            JniError::IllegalArgument(msg)
            | JniError::Runtime(msg)
            | JniError::IllegalState(msg)
            | JniError::UnsupportedOperation(msg)
            | JniError::IndexOutOfBounds(msg)
            | JniError::SecurityException(msg)
            | JniError::Io(msg) => msg.clone(),
            JniError::OutOfMemory => "Out of memory".to_string(),
        }
    }

    /// Throws the corresponding Java exception on `env`.
    ///
    /// An exception already pending takes precedence and is left untouched.
    /// JNI operations commonly report an error because Java code they invoked
    /// threw; replacing that exception here would hide the original cause.
    pub fn throw_on(&self, env: &mut Env<'_>) {
        if env.exception_check() {
            return;
        }
        // `throw_new` returns `Err(Error::JavaException)` once the exception is
        // armed — that is the success path here, so the result is discarded.
        let _ = env.throw_new(self.exception_class(), JNIString::new(self.message()));
    }
}

/// The [`ErrorPolicy`] that maps a [`JniError`] to its specific Java exception.
///
/// The native-method shims generated by `jni_platform_macros` hand this to
/// [`EnvOutcome::resolve`](jni::EnvOutcome::resolve): an `Err(JniError)`
/// returned by a `#[jni_method]` becomes a pending exception of the matching
/// type (NullPointerException, IllegalArgumentException, …) and the method
/// returns the JNI zero value. An exception raised earlier in the method
/// takes precedence and is left in place.
///
/// This is the typed counterpart to the `jni` crate's
/// [`ThrowRuntimeExAndDefault`](jni::errors::ThrowRuntimeExAndDefault), which
/// always throws a plain RuntimeException.
pub struct ThrowJniError;

impl<T: Default> ErrorPolicy<T, JniError> for ThrowJniError {
    type Captures<'unowned_env_local: 'native_method, 'native_method> = ();

    fn on_error<'unowned_env_local: 'native_method, 'native_method>(
        env: &mut Env<'unowned_env_local>,
        _cap: &mut Self::Captures<'unowned_env_local, 'native_method>,
        err: JniError,
    ) -> Result<T> {
        err.throw_on(env);
        Ok(T::default())
    }

    fn on_panic<'unowned_env_local: 'native_method, 'native_method>(
        env: &mut Env<'unowned_env_local>,
        _cap: &mut Self::Captures<'unowned_env_local, 'native_method>,
        payload: Box<dyn Any + Send + 'static>,
    ) -> Result<T> {
        // Platform binaries are built with `panic = "abort"`, so a panic in a
        // native method aborts before reaching here; this path only runs in
        // unwinding builds (e.g. host tests). Surface it as a RuntimeException.
        let msg = payload
            .downcast_ref::<&'static str>()
            .map(|s| s.to_string())
            .or_else(|| payload.downcast_ref::<String>().cloned())
            .unwrap_or_else(|| "native method panicked".to_string());
        if !env.exception_check() {
            let _ = env.throw_new(jni_str!("java/lang/RuntimeException"), JNIString::new(msg));
        }
        Ok(T::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_exception_class_names() {
        assert_eq!(
            JniError::NullPointer("test").exception_class().to_str(),
            "java/lang/NullPointerException"
        );
        assert_eq!(
            JniError::IllegalArgument("test".into()).exception_class().to_str(),
            "java/lang/IllegalArgumentException"
        );
        assert_eq!(
            JniError::Runtime("test".into()).exception_class().to_str(),
            "java/lang/RuntimeException"
        );
        assert_eq!(
            JniError::OutOfMemory.exception_class().to_str(),
            "java/lang/OutOfMemoryError"
        );
        assert_eq!(
            JniError::IllegalState("test".into()).exception_class().to_str(),
            "java/lang/IllegalStateException"
        );
        assert_eq!(
            JniError::UnsupportedOperation("test".into()).exception_class().to_str(),
            "java/lang/UnsupportedOperationException"
        );
        assert_eq!(
            JniError::IndexOutOfBounds("test".into()).exception_class().to_str(),
            "java/lang/IndexOutOfBoundsException"
        );
        assert_eq!(
            JniError::SecurityException("test".into()).exception_class().to_str(),
            "java/lang/SecurityException"
        );
        assert_eq!(JniError::Io("test".into()).exception_class().to_str(), "java/io/IOException");
    }

    #[test]
    fn test_error_messages() {
        assert_eq!(JniError::NullPointer("null ptr").message(), "null ptr");
        assert_eq!(JniError::IllegalArgument("bad arg".into()).message(), "bad arg");
        assert_eq!(JniError::Runtime("oops".into()).message(), "oops");
        assert_eq!(JniError::OutOfMemory.message(), "Out of memory");
        assert_eq!(JniError::Io("disk full".into()).message(), "disk full");
    }

    #[test]
    fn test_display() {
        assert_eq!(format!("{}", JniError::NullPointer("test")), "NullPointerException: test");
        assert_eq!(
            format!("{}", JniError::IllegalArgument("bad".into())),
            "IllegalArgumentException: bad"
        );
        assert_eq!(format!("{}", JniError::OutOfMemory), "OutOfMemoryError");
        assert_eq!(format!("{}", JniError::Io("disk full".into())), "IOException: disk full");
    }

    #[test]
    fn test_from_jni_error_maps_to_runtime_exception() {
        let err: JniError = Error::NullPtr("test ptr").into();
        assert_eq!(err.exception_class().to_str(), "java/lang/RuntimeException");
        assert!(err.message().contains("test ptr"));
    }
}
