//! Android JNI support library.
//!
//! Provides safe Rust abstractions for common JNI patterns found in the
//! Android framework's native code:
//!
//! - [`JniError`] — Typed error enum mapping to Java exceptions
//! - [`ThrowJniError`] — [`ErrorPolicy`](jni::errors::ErrorPolicy) the generated
//!   shims use to turn a `Result` `Err` into the matching pending exception
//! - [`BoundedUtfChars`] — Allocation-free, truncating copy of a Java string
//!
//! A panic that reaches a JNI boundary aborts the process. Android platform
//! binaries are built with `panic = "abort"`, and even in unwinding builds a
//! panic crossing an `extern "system"` function (like the shims generated by
//! `jni_platform_macros`) aborts. This matches the C++ `LOG_ALWAYS_FATAL`
//! convention: a native method that cannot uphold its contract takes down the
//! process loudly rather than continuing in a corrupt state. Use `Result`
//! returns for recoverable errors, and reserve panics for genuinely fatal
//! conditions.

pub mod bounded_utf_chars;
pub mod error;

pub use bounded_utf_chars::BoundedUtfChars;
pub use error::{JniError, ThrowJniError};
